### ISSUE TITLE
Performance issue on Windows machine

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#191]
### Description
When i tried to benchmark Alexnet network using  mkldnn(v0.12) on both windows and linux machines, I observed that  performance  of mkldnn library on linux is far better (1.5 times) compared to windows. Is this difference in performance expected? 
Both windows and linux machines have same configuraion as below except for OS.
### Environment
* PROCESSOR: Intel(R) Xeon(R) CPU E5-1650 v4
* OS :Windows 10
* Library version :Intel MKL_DNN v0.12
* IDE: VS2015
* Toolset: parallel_studio_xe_2017_update4_setup
* Compiler version :Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.4.210 Build 20170411
* CMake version :3.10.2

### Steps to reproduce
To build the library i have followed the below steps :

* Downloaded the source code of the latest version(v0.12).
* Download mklml_win_2018.0.1.20171227.zip manually from GitHub release section and unpack it to the  external directory in mkldnn root directory
* mkdir -p build and cd build
* cmake -G "Visual Studio 14 2015 Win64" -T"Intel C++ Compiler 17.0" ..
* In the build folder open the visual studio solution file and build it in release mode.(Use full optimization)

Please provide your feedback.

Thanks

**Comment by emfomenk** [comment]
Hi,

No, this is not expected. We don't have any OS-specific optimizations.
What benchmark are you using?

Recently we added `MKLDNN_VERBOSE` environment variable that allows dumping each [primitive run time](https://github.com/intel/mkl-dnn/blob/master/doc/perf_profile.md). Could you please update MKL-DNN to the latest version, set `MKLDNN_VERBOSE` to `2`, and dump the result here for both Windows and Linux systems?

Also according to #189 some tests fail on Windows. If that's still the case I think we need to figure out why that happens and only after that it would make sense to measure performance...

**Comment by nhkrishna** [comment]
hi @emfomenk 

I've used the  MKLDNN_VERBOSE environment variable. Noted that for single core,  the execution times for both windows and linux machines are nearly same. But when tried on multi cores(tried on hexacore with hyper threading) , there seems to be major difference in execution times. I've attached the verbose results obtained while running on windows and linux.

[windows1coreverbose2.txt](https://github.com/intel/mkl-dnn/files/1743370/windows1coreverbose2.txt)
[windows12coreverbose2.txt](https://github.com/intel/mkl-dnn/files/1743371/windows12coreverbose2.txt)
[linux1coreverbose2.txt](https://github.com/intel/mkl-dnn/files/1743374/linux1coreverbose2.txt)
[linux12coreverbose2.txt](https://github.com/intel/mkl-dnn/files/1743375/linux12coreverbose2.txt)

Could you suggest on what could be the reason for the performance difference.

Thanks

**Comment by emfomenk** [comment]
Hi,

Thanks for the log!
Seems like Linux scales pretty well, while Windows doesn't.

One issue I found with Windows build was omitted `collapse` pragma. I will soon promote the fix here, meanwhile you can apply it manually. The patch is [attached](https://gist.github.com/emfomenk/bd8adda3a5c3c26fff1dce47418b67c9).
The patch should slightly improve situation on Windows, but definitely would not fix the issue completely since it doesn't change behavior of convolutions and inner products.

As in the case of the bug in the neighbor thread, let's first focus on one particular primitive.
According to the logs you sent the most vivid case is the second convolution: 
`mb1_g2ic96oc256_ih27oh27kh5sh1dh0ph2_iw27ow27kw5sw1dw0pw2`.

The times for it are:

|Linux | Linux                   |   Windows |    Windows |
|------------|-|-|------------------ |
1 thr | 12 thr | 1 thr | 12 thr
9.94 ms | 0.77 ms |  4.66 ms | 2.48 ms

To narrow down the problem I would suggest using [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) -- a standalone convolution benchmark. Could you please verify that you observe the same behavior for the convolution using benchdnn. Here is the run line:
```
$ OMP_NUM_THREADS=6 KMP_AFFINITY=verbose,granularity=fine,compact,1,0 ./tests/benchdnn/benchdnn --mode=PERF --dir=FWD_D -v5 mb1_g2ic96oc256_ih27oh27kh5sh1dh0ph2 mb32_g2ic96oc256_ih27oh27kh5sh1dh0ph2
```

The output should be like this:
```
[... lots of KMP verbose stuff ...]
run: --dir=FWD_D g2mb1ic96ih27oc256oh27kh5ph2n"wip"
mkldnn implementation: jit:avx2
perf,"wip",--dir=FWD_D g2mb1ic96ih27oc256oh27kh5ph2n"wip",0.408969,2.19473,1.07617,380.022,20.9758,19.4972
run: --dir=FWD_D g2mb32ic96ih27oc256oh27kh5ph2n"wip"
mkldnn implementation: jit:avx2
perf,"wip",--dir=FWD_D g2mb32ic96ih27oc256oh27kh5ph2n"wip",13.087,2.19493,116.898,111.953,332.317,39.3811
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):117.974 avg(ms):353.293
```

I intentionally ask to run two convolutions (mb=1 and mb=32) just to check whether the problem is reproducible for both cases. I also want you to try using 6 threads (1 per physical core) instead of 12, cause our experience shows that HT typically doesn't help.  `KMP_AFFINITY` ensures that threads would be pinned to their own cores.

Please run benchdnn with 1 and 6 threads on both Windows and Linux and share your findings.
So far I hope the problem is in incorrect environment or so.

**Comment by nhkrishna** [comment]
Hi @emfomenk 

I manually used your patch `#if defined(_MSC_VER) && !defined(__INTEL_COMPILER)` , still no improvement in performance on windows.
I ran benchdnn with 1 and 6 threads on both linux and windows. 
[windowsbenchdnn6thread.txt](https://github.com/intel/mkl-dnn/files/1748326/windowsbenchdnn6thread.txt)
[windowsbenchdnn1thread.txt](https://github.com/intel/mkl-dnn/files/1748327/windowsbenchdnn1thread.txt)
[linuxbenchdnn6thread.txt](https://github.com/intel/mkl-dnn/files/1748328/linuxbenchdnn6thread.txt)
[linuxbenchdnn1thread.txt](https://github.com/intel/mkl-dnn/files/1748329/linuxbenchdnn1thread.txt)


thanks

**Comment by vpirogov** [comment]
Thanks for taking you time to run this experiment. Minimal times seem to be pretty close for Linux and Windows. The average for batch 1 on Windows is significantly higher and individual measurements show significantly larger deviation for Windows runs.

|mb/time, ms|Linux 1 thr | Windows 1 thr | Linux 6 thr | Windows 6 thr |
| - | - | - | - | - |
| mb1, min ms | 4.1 | 4.2 | 0.7 | 0.9 |
| mb1, ave ms | 4.2 | 5.5 | 1.1 | 3.0 |
| mb32, min ms | 132.1 | 134.4 | 26.9 | 24.2 |
| mb32, ave ms | 132.3 | 136.4 | 30.1 | 31.5 |

It might indicate that you have background process active during the measurements. In general I would expect that running workload with 6 threads, correct KMP_AFFINITY, and no background processess will produce fairly similar results on both systems.
