### ISSUE TITLE
Can mkl-dnn be used in multithread program?

### ISSUE THREAD

**Issue by kobe2000** [intel/mkl-dnn#227]
Hi,
  I want to run same nn model in multipl threads(each is bound to a core) to acheive maximum speed. I can do so using dnn api in MKL. But I doubt I can do so using mkl-dnn, because here operation primitive is built upon memory primitive which difinitely can not be shared among threads. Am I right?

Thanks

**Comment by emfomenk** [comment]
Hi @kobe2000,

You can use mkl-dnn in multi-threaded environment you described with few restrictions:

* primitives are stateful, so if you want to run same convolution in two different threads you need to create two different primitives

* Winograd convolution uses global scratchpad to reduce the memory consumption. that makes it not-thread safe. if you want to use Winograd convolution in multi-threaded case please define `MKLDNN_ENABLE_CONCURRENT_EXEC` (see [details](https://github.com/intel/mkl-dnn/blob/8758fe6ec8a1695b6ac1570b749818a188d0ad66/src/common/scratchpad.cpp#L29)]

Please also go through issue #199 which also devoted to MKL-DNN thread (un)safety.

**Comment by kobe2000** [comment]
You mean the weights is only what can be shared? Do primitives consume memory much? If I construct them in each thread

**Comment by emfomenk** [comment]
Weights can be definitely shared (you just pass the same memory to different convolution primitives).  

When I said primitives are stateful I meant primitives might have internal buffers (like the one that is used for reduction) that makes them not thread-safe.

In general primitives shouldn't consume too much memory. Especially if we are talking about forward pass only. 

One more note. In order to make MKL-DNN sequential you might want to set the number of OMP threads to 1, so that the library would not even try to create a parallel region.

**Comment by kobe2000** [comment]
It really helps, Thank you
