### ISSUE TITLE
Build error on Gentoo hardened

### ISSUE THREAD

**Issue by reyoung** [intel/mkl-dnn#235]
MKL-DNN build error on Sabayon linux. The error is `error: "_FORTIFY_SOURCE" redefined`.

It just like the issue https://github.com/zmap/zmap/issues/7 .  I just changed the following lines in `SDL.cmake`

https://github.com/intel/mkl-dnn/blob/d3835f4df25c3d33a7a2f968c3c9ef26434bfe91/cmake/SDL.cmake#L27-L28
just like this PR https://github.com/zmap/zmap/commit/5e4143973dc71207f087005ee0891b2c86499eae .

```cmake
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -U_FORTIFY_SOURCE")
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -U_FORTIFY_SOURCE")
```
The compile is OK now.

I am not sure whether this is a bug of the cmake files. Should it be merged into upstream?

**Comment by emfomenk** [comment]
Seems like Gentoo changes the default behavior of gcc by putting `_FORTIFY_SOURCE` into list of the predefined macro. See this thread in [Gentoo Bugzilla](https://bugs.gentoo.org/621036) and similar thread to this bug in [MongoDB JIRA ticket](https://jira.mongodb.org/browse/SERVER-29982).

While the fix is pretty simple and straightforward I am not sure it worth putting in Intel MKL-DNN cause it really relates to some particular OS peculiarity.

Short summary:
- (if I read the thread correctly) Gentoo is still evaluating how to proceed with predefining `_FORTIFY_SOURCE`
- MongoDB refuses to apply the patch with `-U_FORTIFY_SOURCE`, blaming Gentoo's tool chain
- zmap applies the patch with `-U_FORTIFY_SOURCE`

@rsdubtso, what do you think?

**Comment by rsdubtso** [comment]
I am inclined to think that we should not apply this patch. Gentoo should know better than just patching their GCC to add `-D_FORTIFY_SOURCE` unconditionally.
