### ISSUE TITLE
difference between various propagation kinds?

### ISSUE THREAD

**Issue by tensor-go** [intel/mkl-dnn#240]
What is the difference between various propagation kinds like forward_inference, forward, forward_training...etc ?
What is the best propagation kind for inference part?

**Comment by emfomenk** [comment]
Hi @tensor-go,

`forward_training` is a propagation kind one has to use during the training. In that case some operations compute extra things required to perform backward pass. For instance, max pooling would store not only the maximums themselves but also indices, where those maximums happen (in a workspace).

`forward_inference` is the best propagation kind for inference, since in that case some of the primitives can skip some operations (e.g. storing indices in a workspace in max pooling). With this prop_kind backward pass is usually impossible (for to lack of information).

`forward` is just an alias for `forward_training`.
