### ISSUE TITLE
MKL DNN Conv2D warm up performance issue

### ISSUE THREAD

**Issue by yehenrytian** [intel/mkl-dnn#242]
I am new to MKL DNN, and I want to use it to perform the 2D Convolution for my project for better performance (Comparing to Eigen). 

However, from my testing, it seems like MKL DNN is slower than Eigen in most cases (especially for smaller Matrixes). It seems to me that MKL has a "warm up" issue. For example, after I built the "convoluton_forward" primitive and insert it into a "net" if I submit the "net" two times for eager execution, the second time is much faster than the first one, e.g.
```
  // 1st execution
  stream(stream::kind::eager).submit(net).wait();
  
  auto startTime = std::chrono::high_resolution_clock::now();
  // 2nd execution
  stream(stream::kind::eager).submit(net).wait();

  auto elapsed = std::chrono::high_resolution_clock::now() - startTime;
  long long microseconds = std::chrono::duration_cast<std::chrono::microseconds> (elapsed).count();
  std::cout << "Conv2D MKL DNN Execution duration is: " << microseconds << "us\n";
```

I am wondering if this is expected, and how can I speed up the execution performance for MKL DNN libraries.  Thanks!

I built MKL DNN from "master" source on the machine below. 
-----------------------------------------------------------------------------

### Environment
Intel MKL-DNN includes hardware-specific optimizations and may behave 
differently on depending on the compiler and build environment. Include 
the following information to help reproduce the issue:
* CPU make and model: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
* OS version: Linux TS-P920-A 4.4.0-124-generic #148-Ubuntu
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* MKLROOT value: /opt/inte/mkl
* CMake version: cmake version 3.5.1
* CMake output log

**Comment by emfomenk** [comment]
I think the behavior might be reasonable -- I can think about at least two factors:
-  if the first convolution run is the one who touches the memory for the first time. In that case you don't only measure the time spent in the primitive itself, but also the time that operating system takes to allocate physical memory and populate it with zeros
- also the subsequent run might be faster because the memory that was used at the first run would now reside in caches

-----

Something that not directly relates to your question, but still.

Intel MKL-DNN has a default benchmark called [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) that might help you to understand what level of performance you might expect from it. You can run it to check that the performance you get in your benchmark matches with benchdnn result. That might help to identify if everything is implemented in the optimal way (Intel MKL-DNN's API is not very convenient to use). :)

Also Intel MKL-DNN has [verbosity feature](https://intel.github.io/mkl-dnn/perf_profile.html). You can set `MKLDNN_VERBOSE`  environment variable to `1` to get the time spent in each and every Intel MKL-DNN primitive. Together with benchdnn it might help you to not write your own micro-benchmark, but rather do the following:

```
$ MKLDNN_VERBOSE=1 ./tests/benchdnn/benchdnn --conv --mode=P mb32ic256oc128ih13kh3ph1
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nchw out:f32_nChw8c,num:1,32x256x13x13,1.09497
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_goihw out:f32_gOIhw8i8o,num:1,1x128x256x3x3,0.738037
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_nchw out:f32_nChw8c,num:1,32x128x13x13,0.858887
mkldnn_verbose,exec,reorder,simple:any,undef,in:f32_x out:f32_x,num:1,128,0.714111
mkldnn_verbose,exec,convolution,jit:avx2,forward_inference,fsrc:nChw8c fwei:gOIhw8i8o fbia:x fdst:nChw8c,alg:convolution_direct,mb32_g1ic256oc128_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1,14.2761
mkldnn_verbose,exec,convolution,jit:avx2,forward_inference,fsrc:nChw8c fwei:gOIhw8i8o fbia:x fdst:nChw8c,alg:convolution_direct,mb32_g1ic256oc128_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1,13.969
mkldnn_verbose,exec,convolution,jit:avx2,forward_inference,fsrc:nChw8c fwei:gOIhw8i8o fbia:x fdst:nChw8c,alg:convolution_direct,mb32_g1ic256oc128_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1,13.9521
...
```

Here you can see that the first run of convolution took `14.2761 ms`, while the second took `13.969 ms` (look at the last number in the lines). So on the system I ran it the difference between the first and the second run was negligible. Benchdnn reorders the data though, which invalidates the first bullet above and partially invalidates the second one (input and weights are my reside in cache due to reorder call). But it all may depend on the sizes of the convolution. So I would suggest you try those experiments on your side.
