### ISSUE TITLE
append_sum usage

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#246]
Hi,

We are trying to understand the optimizations done in intel caffe for resnet_50. Specifically with respect to append_sum where you are fusing the res2a_branch1, res2a_branch2c, sum

Could you let us know how the append_sum is implemented. How does it know which 2 layer outputs need to be added. Since I could not see any buffer information passed as input to append_sum
# ops.append_sum(1.0f);

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

Post-ops API is the lightweight way to merge the operations together. It doesn't change the number of inputs/outputs.

Default convolution works as follows:
```
dst = conv(src, wei)
```
When `append_sum(1.f)` is used the operation performed is:
```
dst += conv(src, wei)
```

This allows merging the residual block in ResNet-50. Basically the convolution updates the previous destination with the result of convolution. Please also check the documentation for [Append_sum](https://intel.github.io/mkl-dnn/group__c__api__attributes__post__ops.html#ga172931a133db5d1a3605495ad877d364).

----

P.S. IntelCaffe goes further. They also merge Relu -- instead of having:
```
r1 (the result of previous residual block)
r2 <-- conv(src, wei)
r3 <-- r1 + r2
r4 <-- relu(r3)
```
they use conv().append_sum().append_relu() which gives:
```
r1 (the result of previous residual block)
r1 <-- relu(r1 + conv(src, wei))
```

This optimization eliminates a bunch of memory reads/writes which leads to substantial performance improvement.

**Comment by uu-praveeng** [comment]
Thank you.
