### ISSUE TITLE
data format reordering

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#250]
Hi,

I have an example network with conv,relu,fc .During the network creation I am passing the conv output memory::primitive as  ReLU input instead of recreating the ReLU memory::primitive. 

If the Conv  output memory primitive has memory::format::data that is not implemented in ReLU how to handle this scenario?Since it will fail saying the data::format is not implemented.
Soultion 1 : Could be to check the data formats supported by ReLU and convert the conv output supported by ReLU using reorders , but this appears to be intrusive.

Instead is there any automated way to query the memory::data::format supported by ReLU and then reorder it accordingly.

This query is not specific to conv->ReLu->Fc but for other networks too. During the runtime if the memory::data::format are automatically updated how could user reorder so that the application do not crash saying that data:;format is not implemented.

Thanks,
G.Praveen.

**Comment by vpirogov** [comment]
I would expect that ReLU supports all possible data formats. Is it a hypothetical scenario or you are observing something odd?

**Comment by uu-praveeng** [comment]
Yes that's right ReLU supports all the data formats. But there are some Layers like lrn that I mentioned in issue (https://github.com/intel/mkl-dnn/issues/251) which do not support some formats.

It would be great if all the layers supports the data format that are given by fully connected and conv layers.

Thank you.

**Comment by shelleygoel** [comment]
I think there is no need to support all formats for LRN, because for better performance LRN should operate on the same memory as output by conv/fc (because reorders are expensive),

**Comment by emfomenk** [comment]
Agree that LRN should support `nc` layout out-of-the-box. Will keep #251 for that.
As of situation in general, if some primitive doesn't support data layout that comes after convolution or inter-product, the proper way to handle that is:

 - reorder data to the native layout, e.g. `nchw` (temporary solution)

  - and file a bug 

There is no point in querying ReLU the format it supports -- it must support whatever comes from other primitives, since ReLU is just an auxiliary primitive for convolution, that is implemented in Intel MKL-DNN to avoid unnecessary conversions between data formats. Hence the situation described in the original post should be treated as a bug.
