### ISSUE TITLE
Any way to add a softmax layer as the output layer based on the "simple_net" sample code?

### ISSUE THREAD

**Issue by xmsjshou** [intel/mkl-dnn#264]
In the mkldnn.hpp, there is no member in **softmax_forward::primitive_desc** named like ones in **inner_product_forward** such as '**src_primitive_desc**' or '**dst_primitive_desc**'.
How to apply the format comparison like the sample code?
BTW, how to add a softmax layer after the FC layers? (based on the structure in sample-net)

-----------------------------------------------------------------------------
Sample code:
```Cpp
auto conv1_src_memory = user_src_memory;
/* Check whether a reorder is necessary  */
if (memory::primitive_desc(conv1_prim_desc.src_primitive_desc())
        != user_src_memory.get_primitive_desc()) {
    /* Yes, a reorder is necessary */
    /* The convolution primitive descriptor contains the descriptor of a memory
     * primitive it requires as input. Because a pointer to the allocated
     * memory is not specified, Intel MKL-DNN allocates the memory. */
    conv1_src_memory = memory(conv1_prim_desc.src_primitive_desc());
    /* create a reorder between user and convolution data and put the reorder
     * into the net. The conv1_src_memory will be the input for the convolution */
    net.push_back(reorder(user_src_memory, conv1_src_memory));
```

**Comment by emfomenk** [comment]
Hi @xmsjshou,

The output of FC is 2D memory in format `nc`. You can create softmax directly on that layout.
Unlike FC that defines the preferable layout, softmax just follows whatever you give it at the creation time. 

See **Performance considerations** section in the [documentation](https://intel.github.io/mkl-dnn/).

So there is no need to check whether you need to use a conversion or not -- the answer would be anyway you don't. And that's why we don't have `softmax_forward::primitive_desc::src_primitive_desc()` -- it is the same as what was used to create corresponding `softmax_forward::primitive_desc`.

**Comment by xmsjshou** [comment]
Hi @emfomenk Thank you for the prompt response.
How to extract data from the results after softmax operation? (For example, to import the data into a specific type of vector?)
Since the vector named "**pipeline**" in "**test_softmax_forward.cpp**" is primitive type? 
I'm still confused about those data format questions.
It would be better if there is any good way to verify the softmax process with modified input.

Here is the code in that Cpp source file:
```C++
......
std::vector<primitive> pipeline;
pipeline.push_back(softmax);
auto s = stream(stream::kind::lazy);
s.submit(pipeline).wait();
......
```
