### ISSUE TITLE
[question] compiler and compiling flags

### ISSUE THREAD

**Issue by cdluminate** [intel/mkl-dnn#292]
Quote from `platform.cmake`

```cmake
 85     if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")                                   
 86         # Clang cannot vectorize some loops with #pragma omp simd and gets      
 87         # very upset. Tell it that it's okay and that we love it                
 88         # unconditionnaly.                                                      
 89         set(CMAKE_CCXX_NOWARN_FLAGS                                             
 90             "${CMAKE_CCXX_NOWARN_FLAGS} -Wno-pass-failed")                      
 91     elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")                           
 92         if(NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0)                     
 93             set(DEF_ARCH_OPT_FLAGS "-march=native -mtune=native")               
 94         endif()                                                                 
 95         if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 6.0)                         
 96             # suppress warning on assumptions made regarding overflow (#146)    
 97             set(CMAKE_CCXX_NOWARN_FLAGS                                         
 98                 "${CMAKE_CCXX_NOWARN_FLAGS} -Wno-strict-overflow")              
 99         endif()                                                                 
100     elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")                              
101         set(DEF_ARCH_OPT_FLAGS "-xHOST")                                        
102         # workaround for Intel Compiler 16.0 that produces error caused         
103         # by pragma omp simd collapse(..)                                       
104         if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "17.0")                      
105             set(CMAKE_CCXX_NOWARN_FLAGS                                         
106                 "${CMAKE_CCXX_NOWARN_FLAGS} -diag-disable:13379")               
107         endif()                                                                 
108         set(CMAKE_CCXX_NOWARN_FLAGS                                             
109             "${CMAKE_CCXX_NOWARN_FLAGS} -diag-disable:15552")                   
110     endif()                       
```

That means `-march=native` and `-mtune=native` is only enabled for GCC >= 5 . However these two flags are not favorable for Debian due to compatibility of the distributed binary. In contrast, when the compiler is Clang, there is no -march=native flag at all. I guess there may be something interesting because previously I indeed observed a performance difference from the machine codes generated by GCC and Clang, on my  neural network program.

1. Why isn't there -march/-mtune flags for Clang?

2. What's the recommended compiler for distributions?

Umm.. maybe I can try `benchdnn` later ...

**Comment by emfomenk** [comment]
Hi @cdluminate,

`-march=native` definitely doesn't work for Debian distribution because it makes binary not _runable_ across different architectures, basically sticking to the hardware where the binary was built and above.

The reason we use `-march=native` is because Intel MKL-DNN is a performance library and we want the best performance for the given architecture. The assumption was that a user would run Intel MKL-DNN at the same system where he built it. For distro repos this is not the case of course. So I would suggest just to put the minimal architecture that Debian is targeting or omit it completely.

The good news is that Intel MKL-DNN uses JIT technique anyways, so the performance should not suffer a lot even if you would not specify `-march=native`.

There is no particular reasons why we don't have this flag when compile with Clang, simply didn't have a reason to do so. Most frameworks use either Intel Compiler or GCC, so that's why added this flags for them. And as I mentioned above this flag doesn't bring a lot of performance improvement in most of the cases anyway.

**Comment by emfomenk** [comment]
Added a warning on the main page about this issue (5daead94452). So close this one.
Please feel free to reopen if you have any further questions or comments.

**Comment by cdluminate** [comment]
@emfomenk Thank you!
