### ISSUE TITLE
Winograd convolution

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#308]
Hi,

I want to create a generic convolution layer using mkl-dnn.
When do I have to use the winograd convolution? Must we provilde the algorithm::undef for auto-selection when creating the descriptors and primitives? Or only use winograd for the 3x3 convolutions?
Also do we have to check if there's a need for workspace memory when using convolutions?
Is Winograd supported on AVX2 haswell cpu's?

thanks,
Filip

**Comment by emfomenk** [comment]
Hi Filip,

Currently Intel MKL-DNN supports only manual dispatching to Winograd algorithm (i.e. you have to pass `algorithm::winograd`). We are currently working on `algorithm::auto`, hopefully that feature would be available soon.

Winograd does not require workspace, just like regular convolutions. I want to note 2 things here though:

1. winograd uses extra space for the winograd transforms. However this extra space is not exposed to the end user, and managed internally in the primitive. We are considering to expose this internal memory as well, because sometimes users want to control all memory allocations happening in their applications.

2. Workspace (in terms of Intel MKL-DNN) is an extra memory you pass to a primitive on forward pass as an output, and pass the same workspace memory to the corresponding primitive on the backward pass as an input. I.e. workspace is an additional required information for a primitive, collected on the forward pass, to be able to compute the backward pass. In case of convolutions all the information required are passed with regular inputs (e.g. diff_dst and weights to compute diff_src).

> Or only use winograd for the 3x3 convolutions?
Winograd is implemented for 3x3 convolutions only. However, not for all the convolutions winograd is faster than direct algorithm. We are working on `algorithm::auto` exactly for the purpose of simplifying users' life -- we will pick winograd algorithm if it's to be faster, and direct algorithm otherwise.

> Is Winograd supported on AVX2 haswell cpu's?

No, winograd is implemented for avx512 only: KNL, KNM, and Skylake+ (server).

**Comment by zeno40** [comment]
Thanks!
that's making a lot clear!
