### ISSUE TITLE
Decounvolution output mismatch

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#314]
Hi,

I have tried to use the deconvolution primitive instead of convolution_backward primitive  to implement the  transposed/de-convolution.

But I see the mismatch in the outputs when I  use the deconvolution primitive . When same input is given  to the convolution_backward primitive ,outputs match.

Dimensions of input, output ,weights and bias are given below
Inputs : batchsize-2, channels-3, height/width-5
outputs : batchsize-2, channels-4, height/width-5
weights : inputchannels-3, outputchannels-4. filterHeight/width-3
bias: size is 4

I have attached both the implementations for your reference . Please let me know If  I am missing anything here.

Thank you.
[deconv_example_setup.tar.gz](https://github.com/intel/mkl-dnn/files/2357475/deconv_example_setup.tar.gz)

**Comment by irinasok** [comment]
Hi,

From your implementation I see that you pass bias to deconvolution primitive, so two primitives (bwd_d conv and deconv) perform different computations. Deconvolution with bias performs bwd_d convolution and adds bias to destination. Bwd_d convolution primitive does not perform any computations with bias.

Thanks,
Irina

**Comment by irinasok** [comment]
One more thing,
When you call convolution bwd_d, physical layout of weights in your example is o=3i=4hw
So when calling deconvolution the layout of weights should be different: o=4i=3hw 
for outputs of deconvolution and bwd_d convolution to match

**Comment by irinasok** [comment]
Sure,

Both convolution and deconvolution in your examples take on input weights in oihw format which states for "output channels, input channels, height, width". However, because convolution and deconvolution act in different directions, source for convolution is a destination for deconvolution and number of input channels for convolution is the number of output channels for deconvolution. This implies that deconvolution and convolution expect different physical layout of weights in memory.

I know it is very confusing, so this is how it works for your example:
conv:
src [n =2, ic = 4, h=w =5]  * wei[oc =3, ic = 4, h=w=5]  = dst[n = 2, oc = 3, h=w=5]

deconv:
src [n =2, ic = 3, h=w =5]  * wei[oc =4, ic = 3, h=w=5]  = dst[n = 3, oc = 4, h=w=5]

To get the same result for deconvolution and bwd_d convolution you should pass source of conv as a destination to deconv, destination of conv as a source for deconv **and transpose weights** from oihw format to iohw. In your code it would be explicit transposition of weights array before passing it to deconvolution.

**Comment by uu-praveeng** [comment]
In the deconv.cpp that I have shared with you has the same dimensions that you specified below

deconv:
src [n =2, ic = 3, h=w =5] * wei[oc =4, ic = 3, h=w=5] = dst[n = 3, oc = 4, h=w=5]

However as per your explaination ,transpose of weights is the one that is missing. 
It would be of great help if you could  update me the deconv.cpp code to do the transpose of weights.

One more point to note is the weights might already have been transposed since the conv_backward.cpp is working as is with the same inputs and weights.

**Comment by uu-praveeng** [comment]
After changing the weights layout . It worked using DeConvolution. Thank you.
