### ISSUE TITLE
Can the BLAS library link to OpenBLAS?

### ISSUE THREAD

**Issue by Laoyian** [intel/mkl-dnn#327]
I see that src/cpu/gemm/os_blas.hpp can use the BLAS library in the system by defining USE_CBLAS and not defining USE_MKL, but I didn't find the relevant options in CMAKE, can I link to Openblas?

Thanks.

**Comment by emfomenk** [comment]
Hi @Laoyian,

Yes, in theory you can link with arbitrary BLAS library as long as it provides cblas interface. We ourselves have never tested this, though.

In order to do that you need:
1. (optional) replace `#include "cblas.h"` to the appropriate one (if the header file has different name)
2. add cmake flags
```cmake
-DCMAKE_C_FLAGS="-DUSE_CBLAS -I/path/to/blas/include -L/path/to/blas/libs -lopenblas" \
-DCMAKE_CXX_FLAGS="-DUSE_CBLAS -I/path/to/blas/include -L/path/to/blas/libs -lopenblas"
```

Please note that Intel MKL-DNN has its own sgemm implementation that is optimized for AVX, AVX2, and AVX512+. See [mkldnn_sgemm](https://intel.github.io/mkl-dnn/group__c__api__blas.html). So the library should perform pretty well even with external BLAS library.

Our ultimate goal is to remove external BLAS-like dependencies at all, which is currently required mostly for the **integer** gemm, and not **single precision** gemm. I don't think OpenBlas supports integer gemm.

Is there a specific reason why you want to link Intel MKL-DNN with OpenBlas?

**Comment by Laoyian** [comment]
@emfomenk Thank you for your reply, I want to link to OpenBLAS because I want to run on a CPU that does not support AVX. I think linking OpenBLAS will make MKL-DNN faster on this CPU.

**Comment by emfomenk** [comment]
Fair :)

In addition to OpenBLAS you can also try linking to libmklml_{intel,gnu}.so which can be easily obtained via [prepare_mkl.sh](https://github.com/intel/mkl-dnn/blob/master/scripts/prepare_mkl.sh) script. Intel MKLML is a subset of the whole [Intel MKL](https://software.intel.com/en-us/mkl) library that is optimized for a broad set of Intel HW, including SSE2, SSE3, SSE4.2, AVX, and above.

**Comment by vpirogov** [comment]
Feel free to reopen this issue or submit a new one if you have any other questions.
