### ISSUE TITLE
Issues about reorder pd creation

### ISSUE THREAD

**Issue by duli2012** [intel/mkl-dnn#335]
I want to create a reorder primitive desc, but get an invalid argument error. 

mkldnn_reorder_primitive_desc_create_v2(...) calls memory_desc_wrapper::consistent_with(...) to check the input/output shape:

inline bool memory_desc_wrapper::consistent_with(
        const memory_desc_wrapper &rhs) const {
    if (ndims() == rhs.ndims()) {
        for (int d = 0; d < ndims(); ++d) {
            if (dims()[d] != rhs.dims()[d]) return false;
        }
        return true;
...}

The above code requires the input shape is the same as the output shape. When reordering data from NHWC format to NCHW. The input/output shapes are not always the same, e.g. [1, 8, 8, 3] -> [1, 3, 8, 8]. Why do we need this checker? How can I create a reorder pd to do NHWC->NCHW reordering?

Thanks a lot.

Du

**Comment by emfomenk** [comment]
Hi @duli2012,

Yeah, this is the most confusing part of Intel MKL-DNN... The short answer is that in both cases the dims should be `[1, 3, 8, 8]`, because [dims](https://intel.github.io/mkl-dnn/structmkldnn__memory__desc__t.html#a0c5fde2a68d65f5e0e7701463a91de50) represent the **logical** dimensions, which always come in order **n**, **c**, **h**, **w** for 4D data tensor.

```c++
// pseudo-code
int n = 1, c = 3, h = 8, w = 8;
memory_desc_t md_in_nchw = {4, {n, c, h, w}, f32, mkldnn_nchw};
memory_desc_t md_in_nhwc = {4, {n, c, h, w}, f32, mkldnn_nhwc}; // note that only format is different

reorder(md_in_nchw, md_in_nhwc); // check is fine -- dims are the same
```

**Comment by duli2012** [comment]
@emfomenk  Got it. Thank you for your prompt response!
