### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by manuelelucchi** [intel/mkl-dnn#353]
Hello, I managed to compile without problems the last release of mkldnn for Windows using Visual Studio 2017 (15.8.9) and a script copied from the CNTK repository. I added it to a Windows C++ project (linked the mkldnn.lib, added headers to path and the mkldnn.dll to the delay load configuration) but when I start the project I get this exception

![image](https://user-images.githubusercontent.com/17146198/48979410-c84ef080-f0ba-11e8-9628-18bde7291b9a.png)

The code is pretty simple, it's a part of the simpleNet example in C++. The exception get thrown at the first function called from mkldnn, so it's obviously a dynamic linking issue. Did I forgot something? 

Regards, 
Manuele

**Comment by emfomenk** [comment]
Hi Manuele,

Intel MKL-DNN dll most likely depends on other libraries (like libiomp5md.dll and libmklml_intel.dll). Do you have both these libraries in your PATH when you run your project?

BTW, why do you delay-load configuration?

**Comment by manuelelucchi** [comment]
Hi , the compilation didn't produce such dlls, can I find them somewhere? I used delay load like the MSFT CNTK, what other configuration do you propose?

**Comment by emfomenk** [comment]
Could you please show the dependencies of the library?
``` cmd
dumpbin /dependents mkldnn.dll
```

Also did you use the same MSVC for building MKL-DNN and CNTK?

You most likely used cmake to build the library. Could you please post its output here as well?

Finally, once the library was built have you tried to run tests to verify it works fine?

> I used delay load like the MSFT CNTK, what other configuration do you propose?

I am not familiar with CNTK but since you are saying this is the default behavior that should be fine. Anyways, there is nothing special about Intel MKL-DNN that would not allow using delay-load with the library.

**Comment by manuelelucchi** [comment]
I didn't built the CNTK but I use it's VS configuration as an example to try linking mkldnn

The dependencies are these 
![image](https://user-images.githubusercontent.com/17146198/48980450-41eddb00-f0c9-11e8-8dc0-a33cd72129c6.png)

To build mkldnn I used this script found on the CNTK repo https://github.com/Microsoft/CNTK/blob/master/Tools/devInstall/Windows/buildMklDnnVS17.bat

**Comment by emfomenk** [comment]
Thanks! The output looks good to me -- Intel MKL-DNN is built without any external dependencies. So that should be fine.

The only guess I have is that `mkldnn.dll` is not in the `PATH` for your project... Might it be the case? Or might be that some other older `mkldnn.dll` is actually in your path?

One of the ways to check that would be to use [ListDLLs](https://docs.microsoft.com/en-us/sysinternals/downloads/listdlls) when your application raises an error:
``` cmd
Listdlls64.exe %APPLICATION_PID%
:: or
:: Listdlls64.exe %APPLICATION_PID% | find /i "mkldnn" 
```

Here `%APPLICATION_PID%` is the PID of the running application that can be found in Task Manager.
If the output would not contain `mkldnn.dll`  that most likely mean the application could not locate the library. If the output is nonempty, please check that the right `mkldnn.dll` is loaded (i.e. the path is correct).

**Comment by manuelelucchi** [comment]
Effectively it doesn't seem to be loaded using listdlls, but it is in both my system path and the visual studio libs path 
![image](https://user-images.githubusercontent.com/17146198/48981606-09a1c900-f0d8-11e8-941f-46a461bb2671.png)
Maybe do you want the Visual Studio solution? it's pretty basic

**Comment by manuelelucchi** [comment]
Update: I tried with cmake instead of msbuild and now the dll i create lists mkldnn.dll as a dependency. But, since i'm calling my dll with loadlibrary, I get NULL apparently because loadlibrary cannot find mkldnn as a dependency of my dll, in fact if I remove mkldnn as a dependency loadlibrary work fine

**Comment by manuelelucchi** [comment]
I saw that link already and tried every answer, even to change the env but it doesn't work. I think it's better to concentrate to che CMake solution

**Comment by rsdubtso** [comment]
Closing due to the lack of activity. Please feel free to reopen.

**Comment by jacobkahn** [comment]
For all those still paying attention, I've just sent along https://github.com/microsoft/vcpkg/pull/15068.
