### ISSUE TITLE
mkl-dnn doesn't pass any unit tests on Windows 10 x64 ?

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#365]
After I download and extract the latest mkl-dnn repo and execute the script to create the external folder and small MKL libraries I can run CMake to generate the Visual Studio 2017 solution just fine. Then I build the whole solution in Visual Studio 2017 and run the unit tests. But strangely all of the units tests fails. It starts with some SegFault message in the first test and all other tests also fails.

A month ago I didn't encouter these problems. I tried it several times and don't know
what I'm doing wrong?

thanks

-----------------------------------------------------------------------------
### Environment
Intel Haswell cpu
Windows 10 Pro x64 version:1809 build:17763.168
Visual Studio 2017 Community 15.9.3
CMake 3.13.0
Intel MKL and TBB are not installed

### Steps to reproduce
see above

### Actual behavior
All unit test are failing

### Expected behavior
All unit test are passing

**Comment by sotoflom** [comment]
Hi,

Most likely the problem is that Visual Studio can't find the .dll for mkldnn (and probably mklml if you're building with MKL dependencies).

The suggested solution is to copy your 'mkldnn.dll' file into the test's executable location (i.e. <project_location>\examples\Debug or <project_location>\tests\Debug).

Here's more info on post-build events to automate this process ([link](https://docs.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=vs-2017#to-copy-the-dll-in-a-post-build-event)).

**Comment by zeno40** [comment]
Thanks for the response. I've copied the files in the correct place now and everything passes the unit tests now.

**Comment by rsdubtso** [comment]
I'm reopening this because the Visual Studio solutions should work out of the box. I could reproduce the issue, but I do not have a fix yet.
