### ISSUE TITLE
Question: Is convolution with signed 8bit source supported?

### ISSUE THREAD

**Issue by SafeteeWoW** [intel/mkl-dnn#375]
I want to do convolution based on the following format:
source(s8), weight(s8), bias(s32) ---> dest(s32)

However, it seems source only supports unsigned 8bit right now.

I am following the example of simple_net_int8.cpp,
but when the memory format of conv_src_md from u8 to s8 does not give me correct output.

Is signed 8 bit source convolution supported? If yes, can you support a sample code?

**Comment by emfomenk** [comment]
Hi @SafeteeWoW,

Can you please try using the latest (master) version of Intel MKL-DNN?
We recently extended support with `s8 (*) s8 --> s32` convolutions.

Here are few implementations:
https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_engine.cpp#L152
https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_engine.cpp#L169

**Comment by SafeteeWoW** [comment]
#include <iostream>
#include <cstdint>
#include <numeric>
#include "mkldnn.hpp"

using namespace mkldnn;
using namespace std;

std::vector<int32_t> run_int8_conv(memory::data_type src_data_type) {
  auto cpu_engine = engine(engine::cpu, 0);

  std::vector<primitive> net;
  std::vector<primitive> net_weight;
  memory::dims conv_src_tz = { 1, 3, 64, 64 };
  memory::dims conv_weights_tz = { 8, 3, 5, 5 };
  memory::dims conv_bias_tz = { 8 };
  memory::dims conv_dst_tz = { 1, 8, 60, 60 };
  memory::dims conv_strides = { 1, 1 };
  auto conv_padding = { 0, 0 };

  auto conv_src_md = memory::desc(
    { conv_src_tz }, src_data_type, memory::format::any);
  auto conv_weights_md = memory::desc(
    { conv_weights_tz }, memory::data_type::s8, memory::format::any);
  auto conv_bias_md = memory::desc(
    { conv_bias_tz }, memory::data_type::s32, memory::format::any);
  auto conv_dst_md = memory::desc(
    { conv_dst_tz }, memory::data_type::s32, memory::format::any);


  std::vector<int8_t> conv_src(std::accumulate(conv_src_tz.begin(),
                                              conv_src_tz.end(), 1, std::multiplies<uint32_t>()));
  std::vector<int8_t> conv_weights(std::accumulate(conv_weights_tz.begin(),
                                                  conv_weights_tz.end(), 1, std::multiplies<uint32_t>()));
  std::vector<int32_t> conv_bias(std::accumulate(conv_bias_tz.begin(),
                                               conv_bias_tz.end(), 1, std::multiplies<uint32_t>()));
  std::vector<int32_t> conv_dst(std::accumulate(conv_dst_tz.begin(),
                                                conv_dst_tz.end(), 1, std::multiplies<uint32_t>()));

  // Fill src, weights and bias with constant values.
  std::fill(conv_src.begin(), conv_src.end(), 1);
  std::fill(conv_weights.begin(), conv_weights.end(), 1);
  std::fill(conv_bias.begin(), conv_bias.end(), 0);

  auto conv_desc = convolution_forward::desc(prop_kind::forward,
                                             convolution_direct, conv_src_md, conv_weights_md, conv_bias_md,
                                             conv_dst_md, conv_strides, conv_padding, conv_padding,
                                             padding_kind::zero);

  auto conv_prim_desc
    = convolution_forward::primitive_desc(conv_desc,  cpu_engine);

  auto user_src_memory
    = memory({ { { conv_src_tz }, src_data_type,
                 memory::format::nhwc },
               cpu_engine },
             conv_src.data());
  auto user_weights_memory
    = memory({ { { conv_weights_tz }, memory::data_type::s8,
                 memory::format::oihw },
               cpu_engine },
             conv_weights.data());
  auto conv_bias_memory = memory(
    { { { conv_bias_tz }, memory::data_type::s32, memory::format::x },
      cpu_engine },
    conv_bias.data());

  auto user_dst_memory = memory(
    { { { conv_dst_tz }, memory::data_type::s32, memory::format::nhwc },
      cpu_engine }, conv_dst.data());

  auto conv_src_memory = user_src_memory;
  if (memory::primitive_desc(conv_prim_desc.src_primitive_desc())
    != user_src_memory.get_primitive_desc()) {
    conv_src_memory = memory(conv_prim_desc.src_primitive_desc());
    net.push_back(reorder(user_src_memory, conv_src_memory));
  }

  auto conv_weights_memory = user_weights_memory;
  if (memory::primitive_desc(conv_prim_desc.weights_primitive_desc())
    != user_weights_memory.get_primitive_desc()) {
    conv_weights_memory
      = memory(conv_prim_desc.weights_primitive_desc());
    net_weight.push_back(
      reorder(user_weights_memory, conv_weights_memory));
  }

  auto conv_dst_memory = memory(conv_prim_desc.dst_primitive_desc());


  net.push_back(convolution_forward(conv_prim_desc, conv_src_memory,
                                    conv_weights_memory, conv_bias_memory,
                                    conv_dst_memory));

  if (conv_dst_memory != user_dst_memory) {
    net.push_back(reorder(conv_dst_memory, user_dst_memory));
  }
  stream(stream::kind::eager).submit(net_weight).wait();
  stream(stream::kind::eager).submit(net).wait();

  return conv_dst;
}


int main(int argc, char **argv) {
  try {
    auto conv_dst_u8 = run_int8_conv(memory::data_type::u8);
    cout << "result[0][0][0][0] " << conv_dst_u8[0] << std::endl;
    auto conv_dst_s8 = run_int8_conv(memory::data_type::s8);
    cout << "result[0][0][0][0] " << conv_dst_s8[0] << std::endl;
  } catch (error &e) {
    std::cerr << "status: " << e.status << std::endl;
    std::cerr << "message: " << e.message << std::endl;
  }
  return 0;
}

**Comment by SafeteeWoW** [comment]
https://gist.github.com/SafeteeWoW/d5a105041e88ba47b47bf2990d26ebc2

In the Gist above, I run signed int8 convolution on:
src : 1x3x64x64, all values filled with 1.
weight: 8x3x5x5, all values filled with 1.
bias: 8, all values filled with 0.

I expect the first value of the output (conv_dst@(0,0,0,0)) should be 75, which is true when I set the memory of src to be memory::data_type::s8. However, I get 0 when I set the memory of src to be memory::date_type::u8.

I am using the latest version on the master branch right now (commit hash 1687299).
My CPU is Xeon E5-2667.
My compiler is gcc 7.3.0
My OS is Linux CentOS 7.3
I compiled MKL-DNN with default configuration with small MKL library https://github.com/intel/mkl-dnn/releases/download/v0.17.2/mklml_lnx_2019.0.1.20181227.tgz

**Comment by emfomenk** [comment]
Thanks for a small reproducer!
I was able to reproduce the issue.
Let me take a look into this and come to you...

**Comment by emfomenk** [comment]
Oh, here is the thing...

This is intentional.
If you change weights fill from `1` to `2` you would get the same (expected) results: 150.

The reason is that during weights reorder we divide all the data by two to overcome possible overflows. In the real world examples (e.g. inference using Intel Caffe that brings minor accuracy drop, but still acceptable). If we would not do that, the accuracy might be much bigger.

Executive summary. The int8 convolutions (on <= Skylake) are defined as:
```
u8 (*) s8 case:
    dst_s32 <- (s32_with_interim_s16) src_u8 (*) wei_s8

s8 (*) s8 case:
    dst_s32 <- 2 * (s32) ((src_s8 + 128) (*) (wei_s8 / 2)) - 128 (*) wei_s8
```

In your example: `wei_s8 = {1, ..., 1}`, hence `wei_s8 / 2 = {0, ..., 0}`, hence the result is 0.

---

Let me try to elaborate why Intel MKL-DNN has such weird behavior (be ready, the explanation is long).
For `u8 (*) s8 -> s32` convolution the real chain of operations on Skylake is:
```
L01     dst_s32 = 0;
L02     for (k = 0 .. dst_size / 2) {
L03        dst_s32 += (s32)(
L04             (s16)src_u8[2k + 0] * wei_s8[2k + 0]
L05             +
L06             (s16)src_u8[2k + 1] * wei_s8[2k + 1]
L07         );
L08     }
```

The intermediate casting to (s16) is caused by ISA. See VPMADDUBSW instruction (some comments can be found in [1](https://en.wikichip.org/wiki/x86/avx512vnni#Motivation)).

Note, that in addition in line (L05) might overflow.
For instance `(s16)255 * 127 + (s16)255 * 127 = -766 (= (s16)64770)`.

Intel MKL-DNN does protect users from this potential overflow. To avoid it either the data should be *good* or input should actually be u7, not u8. Our experience with Intel Caffe int8 inference showed that data distribution is typically good enough and an overflow doesn't happen (speculation: that's because mean(src_u8) << 127). That why we didn't do any changes to this sequence.
// BTW, with VPDPBUSD the problem will be gone [1].

To support a broader set of topologies we had to extend convolution with `s8 (*) s8 -> s32` case. The problem here is that there is no such instructions in ISA. We had to emulate s8 * s8 via u8 * s8. For that instead of computing:
```
    dst_s32 <- src_s8 (*) wei_s8
```
we actual compute:
```
    dst_s32 <- (src_s8 + 128) (*) wei_s8 - 128 (*) wei_s8 = new_src_u8 (*) wei_s8 - compensation_s32
```

Note, that `new_src_u8 (*) wei_s8` follows the same accumulation chain as mentioned above and has the same problem with a potential overflow. But it turned out that this overflow is no more just a potential but typically happens. That makes accuracy go down to almost zero. That's most likely because the data distribution for `new_src_u8` is shifted away from 0 (mean(new_src_u8) = mean(src_s8) + 128 ~= 128).

To make the accuracy good on Skylake again we decided to shrink the weights by factor of two. So the real compute is:
```
    dst_s32 <- 2 * (s32) ((src_s8 + 128) (*) (wei_s8 / 2)) - 128 (*) wei_s8
```

That helped. Note that for HW that supports `VPDPBUSD` there is no need in this magic.

Phew...
So your HW is SandyBridge. Alas, we don't have an optimized int8 support for CPUs below Skylake server. The implementation would emulate s8 * s8 operations using double precision gemm (dgemm). That should be slower than even f32 convolution. But that should be good enough to make tests with int8. The sequence of operations repeat Skylake's ones. Whether this good or not -- I don't know (we've never thought about thoroughly). But we definitely need to document the behavior, to avoid the confusion.

Also we don't have plans to optimize int8 operations for <Skylake (at least for now). Even though this is possible.

Thanks for rising this! And sorry for a long explanation.
Please let me know if you need further details or if the explanation is not clear.

---
[1]. About VNNI on Wiki-chip: https://en.wikichip.org/wiki/x86/avx512vnni
[2]. About INT8 inference on modern Intel HW: https://ai.intel.com/lowering-numerical-precision-increase-deep-learning-performance/

**Comment by SafeteeWoW** [comment]
Thank for your reply.
The behavior on int8 conv definitely should be documented.

I was planning to use mkl-dnn to accelerate our signed int8 convolution. But the acceleration code must be effectively the same as the naive implementation, so I cannot use mkl-dnn due to the precision lost in int8 convolution. I will write intrinsic to accelerate my implementation instead.

Last question, do you have any possible recommend way to optimize s8*s8->s32 on Skylake?

**Comment by emfomenk** [comment]
If your implementation cannot accept the potential overflow in int16 (as described above), that the only way to handle that would be:
```
    src_s16 <-- up-cast src_s8
    wei_s16 <-- up-cast wei_s8
    tmp_s32 <-- VPMADDWD(src_s16, wei_s16)
    dst_s32 <-- VPADD(dst_s32, tmp_s32)
```

But in theory, this sequence would be a little slower than using `vfmadd231ps` in case of f32.

**Comment by emfomenk** [comment]
BTW, this sequence should also work for SandyBridge+ (with XMM registers / _m128i) and Haswell+ (with YMM registers / _m256i).

**Comment by SafeteeWoW** [comment]
Appreciate for your answer. I will try to implement this.
