### ISSUE TITLE
Is there a chance to reuse mkldnn::convolution_forward?

### ISSUE THREAD

**Issue by peteryang1** [intel/mkl-dnn#380]
Suppose I have multiple shape input into the same conv node, I found that I spend a long time(about 30%) in creating `mkldnn::convolution_forward()`, then after one use, I deconstruct it. 

I try to store the `mkldnn::convolution_forward()` and reuse it when shape is the same, but I found it costing a lot of memory.

Is there a chance that I construct one `mkldnn::convolution_forward()` and reuse it when shape changed?

looking forward to your answer!

**Comment by peteryang1** [comment]
I found that I can use global_scratchpad_ to reduce buffer's size (only store the biggest buffer), but I found `jit_generator` costs a lot of memory, do you have any idea why `jit_generator` takes so much memory?

**Comment by emfomenk** [comment]
Hi @peteryang1,

Unfortunately, it is not possible to use any Intel MKL-DNN primitive for the shapes that don't match the one you used at creation time. The reason is that Intel MKL-DNN generates very specific code for a given shape and sizes.

I am somewhat surprised that forward convolution consumes a lot of memory. It used to do that in older versions for gemm-based implementation (which is a fallback and ideally should not appear at all). The reason is that gemm-based implementation requires reordering the data from image to a so-called column format.

But in recent versions of Intel MKL-DNN we made gemm-based implementation to use global scratchpad. So memory consumption should be limited to one (most memory-consuming) convolution.

_While I was typing you have already figured that out_ :)

`jit_generator` contains all the stuff it needs to generate the binary code. But I would not expect it to be more that several MB. How big is jit_generator in your case?

**Comment by peteryang1** [comment]
Firstly, I found that the buffer is only created in `jit_avx2_1x1_convolution_fwd_t` and it is very big, maybe you can see why this class needs the buffer.

Secondly, each jit_generator costs about 250k in my runtime, but a model has 100 conv nodes can increase about 35MB memory.

**Comment by emfomenk** [comment]
Let me guess, your 1x1 (`kh=kw=1`) convolutions have non-trivial stride (bigger than 1).
In this case the implementation allocate an extra space to reduce the source (input) to the data w/o strides. So roughly the buffer would be of size `sizeof(source) / stride_h / stride_w`.
The implementation doesn't use global scratchpad, so every new convolution would consume it's own memory.

A silly workaround I can suggest is to use `mkldnn_query_memory_consumption_s64` query we recently implemented. For a given primitive descriptor you can query how much memory the primitive would consume. So if the consumption is less than some threshold you would cache them and don't cache otherwise.


250 Kb for `jit_generator` seems reasonable. Mostly that is due to the memory descriptors that we keep inside -- every structure contains information about dimensions, block sizes for this dimension, strides, padding and others. Since the library supports up to 16 number of dimensions, that costs.

**Comment by emfomenk** [comment]
Actually I am talking my words back.
The `jit_generator` it self is not big, as well as any primitive descriptors:

```
(gdb) p sizeof(mkldnn::impl::cpu::jit_avx2_convolution_fwd_t::pd_t)
$5 = 12048
(gdb) p sizeof(mkldnn::impl::cpu::jit_avx2_1x1_convolution_fwd_t::pd_t)
$6 = 15352
(gdb) p sizeof(mkldnn::impl::cpu::jit_generator)
$7 = 2112
```

256 Kb you mentioned above is a dynamically allocated buffer for the generated binary code.
Since the library generates the code for the primitives it needs to store it. So if you preserve 100 primitives (for a topology) times 100 topologies (due to different shapes) you would essentially preserve 100 x 100 small binaries. That is expected behavior, I would say. 256 Kb maybe is an overkill (this is basically an upper bound), but the codes of size 32 Kb are quite common.

And of course those buffers cannot be reused, since they store the generated code, which is read-only.

The best solution here would be implementing a cache with some fixed capacity and having some heuristics of eviction like LRU or something.

Just out of curiosity, when you say you have different input shapes, are you talking about arbitrary dimension? Or some particular, like minibatch?

**Comment by peteryang1** [comment]
first I apologize for not expressing my intention clearly, 

250K is from me recording the memory heap before and after this line:
```C++
kernel_ = new jit_avx2_1x1_conv_kernel_f32(pd()->jcp_, *pd()->attr());
```
the heap rises about 250KB. 

I am making an model allows different size of height and width input, so I need to run my model in different shape from the user's input (same in each conv node).

Surely I think an LRU like algorithm may be the solution to my problem. And I found that with the input tensor gets bigger the time costs in creating `mkldnn::convolution_forward()` gets longer, 

In my runtime, if I construct `mkldnn::convolution_forward()` in each execution, the time costs in conv almost doubled. Maybe you can improve it by some way.

Still thanks a lot for your help!

**Comment by emfomenk** [comment]
> I am making an model allows different size of height and width input, so I need to run my model in different shape from the user's input (same in each conv node).

In this case, unfortunately, the code generated would be definitely different. So there is no way to workaround this.

But the slow creation might be actually caused by sequential picking of the best parameters for the kernels. We've never optimized that part (for instance we sometimes need to decompose the number into factors, and we might simply iterate over numbers to find the best decomposition).

So if you can give us some examples where generation takes too long we can at least profile and check whether this is reasonable or something stupid going on...

**Comment by peteryang1** [comment]
I may got it why my construction of the conv node (construct `mkldnn::convolution_forward()`) takes so long time,

 I found it that a depthwise conv( which group == input_channel)'s construction takes a lot of time. maybe you can check it.

like a conv:
input_tensor: 1*32*100*100(nchw)
kernel: 32*1*1*1
bias:32
groups:32

I will try to locate the problem more specifically.

**Comment by emfomenk** [comment]
Hi @peteryang1,

Thanks for the information!
Could you please run your application with `MKLDNN_VERBOSE` environment variable set to `2` and post the output? The verbose would print all the shapes and other parameters for convolutions (and other primitives). It also would print how much time was spent in creation and execution of primitives.

There are two reasons for this ask:
- to get a baseline in ms for the creation time (and also compare it with others)
- to get the exact input parameters

You are saying the kernel is `32 x 1 x 1 x 1`. Shouldn't it be `32 x 1 x 1 x 1 x 1`?
Also why the format is `nchw`? Do you force it to be `nchw` or do you create a convolution with `any` and that the format the convolution required?

**Comment by emfomenk** [comment]
I also took a quick look at the sources (depthwise jit convolution and gemm-based convolution) and didn't find anything suspicious. At least at first glance. Once you provide a verbose output I will make more thorough investigation.

Could you please confirm you use one of the latest Intel MKL-DNN?

**Comment by peteryang1** [comment]
I used the latest master branch, and after rebuilding the mkldnn, the speed gets right.....
