### ISSUE TITLE
Incorrect Reordering for the Inputs and Outputs of the convolution Layer in the mkldnn v0.17

### ISSUE THREAD

**Issue by BhaskarsarmaP** [intel/mkl-dnn#381]
Conv Layer behaving incorrectly for the below dimensions
when Tried in the MKLDNN v0.17.2 layer, For conv layer
Our Input data is in format nchw8c i.e n=1,c=512,h=46,w=34
Our Output data is in the format nchw i.e n=1,c=22,h=46,w=34 ;
After Configure, The data formats were reformatted to nchw8c which was not ideal case.
As the output cannot be converted into nchw8c format.
These inputs and outputs should be of data format nchw after the configure which was happening in v0.14

**Comment by BhaskarsarmaP** [comment]
We have used 'any' for oprimization purposes . 
However the output channel sizes are not multiple is 22 which is not multiple of 8 . So the Convolution should fallback to nchw instead of operating on nChw8c .
Note: In v14 the same convolution is operating with nchw for both input and output.

**Comment by emfomenk** [comment]
Starting with v0.15 Intel MKL-DNN supports padding. So 22 channels would be rounded up to 24 so that optimized jitted convolution is used. This should be more or less transparent to user. The only pitfall is that allocation should be done for appropriate size (which is bigger than just product of logical dimensions). However if a user uses `mkldnn_memory_primitive_get_size()` everything should be fine.

The information about padded format can be found in this [article](https://intel.github.io/mkl-dnn/understanding_memory_formats.html).

**Comment by BhaskarsarmaP** [comment]
Ok Thanks for the Information
