### ISSUE TITLE
Advice on adaptation of future mkl-dnn 1.0

### ISSUE THREAD

**Issue by jczaja** [intel/mkl-dnn#445]
Hi,

We are working on PaddlePaddle lib that is using MKL-DNN. We would like to prepare
PaddlePaddle for MKL-DNN 1.0 integration. I read with great interest:
https://github.com/intel/mkl-dnn/tree/rfc-api-changes-v1.0/doc/rfc/api-v1.0

My concern is that PaddlePaddle for each tensor does record mkl-dnn format name, which may be difficult/unavailable when MKL-DNN 1.0 is used as based on RFC:

> Users will still be able to initialize memory descriptors with format tags like nchw, but the memory_desc_t.format_kind will be set to a canonicalized kind like blocked, and the **format name will not be recorded in the memory descriptor structure**. Initialization with strides will always result in blocked format. The API will also use different types for memory format tags and kinds to aid correctness.

Questions:
1) If we use "any" name to work with computational primitive, then in PaddlePaddle we 
    get format name from primitve_desc::desc() . According to RFC this no longer be possible?
2) Will it be to possible to do  similar  "hacky" guess  based on physical strides & block sizes eg. to guess that it is nchw16c  based on size of blocked format as described by memory descriptor structure? 
3) What is your recommendation in terms of registering MKL-DNN data in Tensor? Should we switch to recording primitive_desc or stay with memory format recording? 
4) Are you planning further changes to API of mkl-dnn 1.0  before 1.0 release, or API of 1.0 is stable and will be as in  Preview of MKl-DNN 1.0 :
https://github.com/intel/mkl-dnn/releases/tag/v1.0-pc
?

**Comment by emfomenk** [comment]
Hi @jczaja,

Thanks for good questions!

> My concern is that PaddlePaddle for each tensor does record mkl-dnn format name, which may be difficult/unavailable when MKL-DNN 1.0 is used

In general I would say PaddlePaddle should keep the whole mkl-dnn memory descriptor instead of just format name. Keeping MD should be enough to fully specify the memory (assuming the engine is the same everywhere).

Coming back to your questions:

> 1. If we use "any" name to work with computational primitive, then in PaddlePaddle we
get format name from primitve_desc::desc() . According to RFC this no longer be possible?

The short answer is **yes**, you cannot get the format name out of memory descriptor.

The long answer is that memory descriptor contains all the information about the format. What you did before was taking the whole memory desc and grabbing only the format name out of it. That was enough to recreate a new memory by knowing the shape (known by FWK), data type (known by FWK), and format name (not known by FWK, but preserved by the format name). Now you better keep the whole memory descriptor and that should allow you to recreate memory if necessary.

> 2. Will it be to possible to do similar "hacky" guess based on physical strides & block sizes eg. to guess that it is nchw16c based on size of blocked format as described by memory descriptor structure?

While I would not recommend that, this is of course possible since the memory descriptor is a transparent structure with well defined semantics. For instance `nChw16c` essential means that:
``` cpp
    auto &bd = md.format_desc.blocking;
    assert(true
        && bd.inner_nblks == 1    // only one dimension is blocked
        && bd.inner_blks[0] == 16 // block size
        && bd.inner_idxs[0] == 1  // c is the 1st dimension
    );
```

> 3. What is your recommendation in terms of registering MKL-DNN data in Tensor? Should we switch to recording primitive_desc or stay with memory format recording?

Just memory descriptor.

> 4. Are you planning further changes to API of mkl-dnn 1.0 before 1.0 release, or API of 1.0 is stable and will be as in Preview of MKl-DNN 1.0:  https://github.com/intel/mkl-dnn/releases/tag/v1.0-pc?

Yes, but really minor (like few renamings here and there). But there should not be any *conceptual* changes. That was exactly the purpose of publishing the 1.0-pc for people to see the conceptual changes as soon as possible.

**Comment by jczaja** [comment]
@emfomenk Thanks very much for very detailed answers.
