### ISSUE TITLE
Convolution and avx2/avx512

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#446]
We are wondering why Convolution is not converting input `nchw` to `nChw8c` in 2nd case.

**Case 1:**
Convolution primitive is created with input format set to `format:nchw` and output to `format:any`.
and we get 
`conv_forward_pd.weights_primitive_desc().desc().data.format` is `f32_Ohwi8o`.
`conv_forward_pd.dst_primitive_desc().desc().data.format` is `nChw8c`

so, this is good.

```
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_oihw out:f32_Ohwi8o,num:1,16x3x3x3,0.00379992
mkldnn_verbose,exec,convolution,jit:avx2,forward_training,fsrc:nchw fwei:Ohwi8o fbia:undef fdst:nChw8c,alg:convolution_direct,mb1_ic3oc16_ih416oh416kh3sh1dh0ph1_iw416ow416kw3sw1dw0pw1,6.1933
```
**Case 2:**
create pool primitive, src format set to `nchw`. It's output is also `nchw`.
set convolution src memory desc to pool's primitive dst desc (block propagation) 
set convolution dst memory desc to `format::any`
but now
get weights format from `conv_forward_pd.weights_primitive_desc().desc().data.format` is `f32_oihw`.
get dst format from `conv_forward_pd.dst_primitive_desc().desc().data.format` is `nchw`.

How do I force Convolution to use nChw8c and f32_Ohwi8o for better performance?
There are many Convolutions to follow and perf is dropping because of this.

```
mkldnn_verbose,exec,reorder,jit:uni,undef,in:f32_oihw out:f32_oihw,num:1,32x16x3x3,0.0795001
mkldnn_verbose,exec,pooling,nchw_pooling:any,forward_inference,fdata:nchw fws:undef,alg:pooling_max,mb1ic16_ih416oh208kh2sh2ph0_iw416ow208kw2sw2pw0,65.3815
mkldnn_verbose,exec,convolution,gemm:jit,forward_training,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb1_ic16oc32_ih208oh208kh3sh1dh0ph1_iw208ow208kw3sw1dw0pw1,388.003
```

**Comment by igorsafo** [comment]
Hi @dev2y ,

Convolution (and inner product) is a primitive which should be always created with format::any for all memory descriptors (except bias, i think). Then reorders should be created to reorder data into format suitable for this particular convolution implementation. When user passes some particular format like format::nchw it limits MKL-DNN in choosing best available implementation. Other primitives like pooling should be created on top of memory descriptor coming from convolution if there is a convolution before this primitive.
In Case 1 optimized convolution is executed because it is a corner case. We have a special implementation for the first convolution (ic = 1,2,3), which allows us to avoid an additional reorder before the first convolution in topology. Case 2 is a regular case so it is expected that convolution will go into gemm-based or reference implementation.

**Comment by dev2y** [comment]
@igorsafo 

case 2. I tried executing convolution, without block propagation. With src set to format::any and dst set to format::any.  I see that Convolution is executing using AVX. 

But if use memory and memory description from previous node (pool primitive), I see that Convolution is using gemm. Why Convolution is not using AVX when it gets memory block from previous node?

**Comment by igorsafo** [comment]
I am assuming pooling has format::nchw for destination. Since convolution was created on this format it prevents mkl-dnn from choosing AVX implementation, because AVX implementation requires format::nChw8c for source. So mkl-dnn chooses gemm-based implementation, because it supports format::nchw for source.
  In case of format::any mkl-dnn takes AVX implementation. Ideally mkl-dnn execution flow in application should be something like this: user_data(nchw) -> reorder(nchw, blocked) -> conv(blocked) -> pooling(blocked) -> ... -> reorder(blocked, nchw/nc) -> user_data , where all convolution are created on format::any and "blocked" is a format convolution decided to have for source and destination.

**Comment by dev2y** [comment]
I now understand ideal mkldnn execution flow and it makes sense. Thanks.

in order to reorder input data from nchw to blocked, we need to know the blocked memory format (nchw8c or nchw16c). How will I find out blocked memory format for the given hardware?

user_data(nchw) -> **reorder(nchw, blocked)** -> conv(blocked) -> pooling(blocked) -> ... -> reorder(blocked, nchw/nc) -> user_data

**Comment by shelleygoel** [comment]
You have to query the convolution primitive descriptor for the input  descriptor. Refer to simple net  example to [query src desc](https://github.com/intel/mkl-dnn/blob/dd963e5a0f2ff4099b9442e50c38c9cc9bfac29b/examples/simple_net.cpp#L94-L102) and create reorders.

 `src_desc().format` should give you the name of the format used.

When you create a convolution primitive descriptor, it is able to identify the architecture and choose the appropriate format.

**Comment by dev2y** [comment]
@shelleygoel 

Yes. We can query Convolution to get the blocked memory format but per execution flow, we want to reorder input data to blocked, before we execute Convolution.

**Comment by shelleygoel** [comment]
For the optimized path, one should _execute a reorder_ after creating a convolution primitive.  Note primitive creation and execution are two separate  workflows.  Ideally you would create all the primitives in the network before executing the network, like in the example [here](https://github.com/intel/mkl-dnn/blob/dd963e5a0f2ff4099b9442e50c38c9cc9bfac29b/examples/simple_net.cpp#L718-L722).
