### ISSUE TITLE
Question on broadcasting of data

### ISSUE THREAD

**Issue by jczaja** [intel/mkl-dnn#449]
Hi,

PaddlePaddle does broadcast data quite often in their primitive . For example, elementwise sum (http://www.paddlepaddle.org/documentation/docs/en/1.3/api/layers.html#permalink-62-elementwise_add) accept two parameters A and B. A dims can equal to B dims then mkl-dnn sum can be used, but in second mode A dims are multiplication of B dims . For example
shape(A) = (2, 3, 4, 5), shape(B) = (4, 5). So B will be "brodcasted" so it match A dims. B has to be "continuous sub-sequence" of A. It is like we multiply data of B so multiplied buffer matched
A dims and then elementwise sum can take place. 

Could you please advice how to implement broadcasting with MKL-DNN ? I can see three options: 1) Implement broadcasting support within primitive 2) use "views" so We get  
part of A buffer at time to do elementwise summing and then change view to another area of A buffer?  3) We could create memory PD to simulate view , by changing pointer of A buffer (set_data_handle to A then set_data_handle to A+offset ...) .However considering physical padding that MKL-DNN may add, I 'm not sure if this will work ?

Please advice on how you recommend we proceed.

**Comment by emfomenk** [comment]
Hi @jczaja,

Yeah, option 1 seems as the most viable. The main issues with options 2 and 3 that would really slow and awkward since you would basically simulate broadcast youself (by calling Intel MKL-DNN sum multiple times).

Another trick you can use is creating a memory with strides equal 0 for the dimensions you want to broadcast. An example posted [here](https://gist.github.com/emfomenk/9080e7c57aa7e7237c9dac3a737b1060). It implements bcast for 
```
A: 2 x 3 x 2 x 2 (format: nchw)
B:     3 x 2     (format:  ch)
```

The only purpose of this example is to demonstrate how potential the corresponding primitive can look like in the library. I definitely do not suggest users generalize this code (basically the code depends on the format).

On the other hand, have you considered reorder the data back to the native PaddlePaddle layout (if necessary) and emit the regular bcast operation? Does it hurt performance too much?

**Comment by vpirogov** [comment]
We are looking at potential support of tensor algebra extensions with limited broadcast support in the library, but this is still in the exploration stage.

**Comment by jczaja** [comment]
@emfomenk , @vpirogov Thanks very much for answers, comments and very interesting example on strides manipulations . We will be interested to try MKL-DNN broadcasting support as soon as it is available.
