### ISSUE TITLE
Gemm-based convolution seems to support only single threads

### ISSUE THREAD

**Issue by nwpu2fjl** [intel/mkl-dnn#454]
My MacBook Pro has 4 Cores and 8 Physical threads(Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz).
When I have compiled mkldnn and integrated it into my application  I run it with different threads by export OMP_NUM_THREADS=x. My test result is as below. It seems the numbers of threads is nothing to do with the performance.
![image](https://user-images.githubusercontent.com/12624852/55937993-eafa3400-5c6c-11e9-8efd-6d228e8c6487.png). Am I right?

**Comment by emfomenk** [comment]
Hi @nwpu2fjl,

Most likely you use standard clang compiler from OS X which doesn't support OpenMP. You can check that by reading the log of `cmake ..`. If you see something like the one below, that means you built Intel MKL-DNN w/o OpenMP support:

```
-- ...
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
CMake Warning at cmake/OpenMP.cmake:115 (message):
  OpenMP library could not be found.  Proceeding might lead to highly
  sub-optimal performance.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)
-- ...
```

The way to workaround this is to either install clang-omp from brew or some other compiler that supports OpenMP.

**Comment by vpirogov** [comment]
Another option will be using TBB threading by passing MKLDNN_THREADING=TBB to CMake.

**Comment by nwpu2fjl** [comment]
That's very kind to say thanks. As you say, My  `cmake ..` log is as below.
```
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
CMake Warning at cmake/OpenMP.cmake:115 (message):
  OpenMP library could not be found.  Proceeding might lead to highly
  sub-optimal performance.
Call Stack (most recent call first):
  CMakeLists.txt:76 (include)
````
But when I  opened MKLDNN_USE_MKL by `cd scripts && ./prepare_mkl.sh && cd ..`,  then I tried different threads by  `export OMP_NUM_THREADS=x` and I got the expected change in my application.

|export OMP_NUM_THREADS=x | 1  | 2 | 4 | 8 |
| --- | --- | --- | --- | --- |
|time(ms) |  552.382690 ms | 468.902771 ms | 449.384674 ms | 491.986877 ms |

**Comment by nwpu2fjl** [comment]
Maybe I know the answer. 
mkldnn
  - depend on openmp(clang compiler from OS X which doesn't support OpenMP, so print OpenMP library could not be found.)
  - depend on mklml(mklml support OpenMP, so cause different performance after importing mkl )
     - mklml depend on iomp5

After installing the clang-omp,  Cmake still can't find OpenMP Library.
`brew install libomp`

**Comment by nwpu2fjl** [comment]
Through export KMP_AFFINITY=verbose,  the thread info have been printed in ubuntu.
```
root@6a96c0bc4589:~/volume/mkl-dnn/build/examples# export KMP_AFFINITY=verbose
root@6a96c0bc4589:~/volume/mkl-dnn/build/examples# ./simple-net-c
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #213: KMP_AFFINITY: x2APIC ids not unique - decoding legacy APIC ids.
OMP: Info #149: KMP_AFFINITY: Affinity capable, using global cpuid info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-3
OMP: Info #156: KMP_AFFINITY: 4 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #159: KMP_AFFINITY: 4 packages x 1 cores/pkg x 1 threads/core (4 total cores)
OMP: Info #250: KMP_AFFINITY: pid 8196 tid 8196 thread 0 bound to OS proc set 0-3
mkldnn_verbose,info,Intel(R) MKL-DNN v0.90.0 (Git Hash dd963e5a0f2ff4099b9442e50c38c9cc9bfac29b),Intel(R) Advanced Vector Extensions 2 (Intel(R) AVX2)
OMP: Info #250: KMP_AFFINITY: pid 8196 tid 8197 thread 1 bound to OS proc set 0-3
OMP: Info #250: KMP_AFFINITY: pid 8196 tid 8198 thread 2 bound to OS proc set 0-3
OMP: Info #250: KMP_AFFINITY: pid 8196 tid 8199 thread 3 bound to OS proc set 0-3
mkldnn_verbose,exec,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:Acdb8a:f0,num:1,96x3x11x11,4.26807
mkldnn_verbose,exec,convolution,jit:avx2,forward_training,src_f32::blocked:abcd:f0 wei_f32::blocked:Acdb8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,alg:convolution_direct,mb8_ic3oc96_ih227oh55kh11sh4dh0ph0_iw227ow55kw11sw4dw0pw0,11.429
mkldnn_verbose,exec,eltwise,jit:avx2,forward_training,data_f32::blocked:aBcd8b:f0,alg:eltwise_relu,8x96x55x55,1.78296
mkldnn_verbose,exec,lrn,jit:avx2,forward_training,data_f32::blocked:aBcd8b:f0,alg:lrn_across_channels,mb8ic96ih55iw55,4.87305
mkldnn_verbose,exec,pooling,jit:avx,forward_training,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:aBcd8b:f0 ws_u8::blocked:aBcd8b:f0,alg:pooling_max,mb8ic96_ih55oh27kh3sh2ph0_iw55ow27kw3sw2pw0,3.85693
mkldnn_verbose,exec,reorder,jit:uni,undef,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:abcd:f0,num:1,8x96x27x27,0.943115
passed

```
And `cmake .. ` log is as below
```
-- Detecting Intel(R) MKL: trying mklml_intel
-- Intel(R) MKL: include /root/volume/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/include
-- Intel(R) MKL: lib /root/volume/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libmklml_intel.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMAKE_VERSION VERSION_LESS 3.9" AND OPENMP_FOUND"
-- OpenMP lib: /root/volume/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/lib/libiomp5.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/volume/mkl-dnn/build
```

**Comment by emfomenk** [comment]
Hi @nwpu2fjl,

Your guess about Intel MKL-DNN being dependent on Intel MKL-ML which in turn depends on libiomp5.dylib was absolutely correct.

Installing `libomp` library is not enough since the clang compiler itself should support OpenMP. So you need clang-openmp or something like that. Please also note that if use non-standard compiler you would have to tell about cmake about that. Something like

``` bash
CC=/path/to/omp-enabled/clang CXX=/path/to/omp-enabled/clang++ cmake ..
```

**Comment by emfomenk** [comment]
Also, regarding the time scalability you observed.

>  export OMP_NUM_THREADS=x | 1 | 2 | 4 | 8
> -- | -- | -- | -- | --
> time(ms) | 552.382690 ms | 468.902771 ms | 449.384674 ms | 491.986877 ms

The thing is that Intel MKL-ML is already built library which relies on OpenMP. So that means that Intel MKL-ML sgemm (that is call by a convolution) would be parallelized. That is why you see better time with increasing the number of threads. The reason why this scalability is so weak is (most likely) due to the other part of the convolution algorithm, called **im2col**. This part is fully implemented on Intel MKL-DNN side which in your case doesn't utilize threads and seems to be a bottleneck in this case.

**Comment by nwpu2fjl** [comment]
@emfomenk , thanks very much, Your opinion is very useful.

**Comment by nwpu2fjl** [comment]
I use /usr/local/bin/clang-omp && /usr/local/bin/clang++-omp to compile mkldnn with OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp" and it seems works.(I have excluded the dependency of mklml), and then test performance by simple-net-cpp:

![image](https://user-images.githubusercontent.com/12624852/56122713-98d74c80-5fa5-11e9-904c-446aebfda220.png)

| OMP_NUM_THREADS  | 1 | 2 | 4 | 8 |
| --- | --- | --- | --- | --- |
| Simple-net-cpp | 51.48 |  49.01 | 46.3 | 45.27 |

**Comment by emfomenk** [comment]
Hi @nwpu2fjl,

I wasn't able to reproduce the behavior you observe. I tested 2 configurations and in both cases `simple-net-cpp` scales (to some extend).

- **Configuration 1** Os X @ i7-2620M (pretty old Sandy Bridge) with 2 cores (4 HW Threads).

| **OMP_NUM_THREADS** | 1 | 2
| :-- | :-- | :--
| simple-net-cpp | 66.84 | 40.79

- **Configuration 2** Linux @ Xeon 2699v4 (Broadwell Server) with 22 cores (22 HW Threads)

| **OMP_NUM_THREADS** | 1 | 2 | 4
| :-- | :-- | :-- | :--
| simple-net-cpp | 61.31 | 31.79 | 17.31

In both cases I used Clang8 with OpenMP from LLVM. No Intel MKL-ML.

So the results you are showing seem strange to me. Essentially I would I see no scaling at all (few percent for 2 and 4 cores -- this is definitely is not how it should be).

Could you please confirm you changed nothing in the example? In particular you haven't changed the number of iterations to a small number (say 1 or 2). By default it is set to 100 which allows reduce the overhead of a warm up run.

Also could you please run **benchdnn** (Intel MKL-DNN performance and correctness micro-benchmark) to test convolution performance:
``` bash
( for omp in 1 2 4; do echo "omp:$omp"; OMP_NUM_THREADS=$omp ./tests/benchdnn/benchdnn --conv --mode=P mb32_ic128oc128_ih13kh3ph1 mb32_ic128oc128_ih13kh1ph0; done )
```

Here benchdnn executes 2 convolutions (one 3x3 and one 1x1) and reports the performance.
For instance I got the following number on my OS X with SandyBridge (I didn't run benchdnn for 4 omp threads since the system has only 2 cores):

```
omp:1
perf,"wip",mb32ic128ih13oc128oh11kh3n"wip",1.1419,0,26.6883,42.7865,29.293,38.982
perf,"wip",mb32ic128ih13oc128oh13kh1n"wip",0.177209,0,3.67154,48.2657,4.1563,42.6364
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):30.3598 avg(ms):33.4493
omp:2
perf,"wip",mb32ic128ih13oc128oh11kh3n"wip",1.1419,0,14.2481,80.1441,15.4903,73.717
perf,"wip",mb32ic128ih13oc128oh13kh1n"wip",0.177209,0,1.98316,89.3572,2.07146,85.5481
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):16.2312 avg(ms):17.5618
```

The numbers of interest are the 4th and 3rd from the end. The 4th number reports the best time for the given convolution (in ms), the 3rd number reports the best performance for the given convolution (in GFlops). In my case:

| **OMP_NUM_THREADS** | 1 | 2
| :-- | :-- | :--
| 3x3 | 26.7 ms (42.8 GFlops)  | 14.3 ms (80 GFlops)
| 1x1 | 3.7 ms (48.3 GFlops) | 1.98 ms (89.3 GFlops)

**Comment by nwpu2fjl** [comment]
Oh, I have reproduced your result on My OS X（i7-4870HQ), but seems it failed to use omp. And I will try it until getting the right result. Thx.
```
omp:1
perf,"wip",mb32ic128ih13oc128oh11kh3n"wip",1.1419,0,14.1482,80.7097,15.1275,75.4849
perf,"wip",mb32ic128ih13oc128oh13kh1n"wip",0.177209,0,1.93522,91.5705,2.10508,84.1819
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):16.0834 avg(ms):17.2326
omp:2
perf,"wip",mb32ic128ih13oc128oh11kh3n"wip",1.1419,0,14.0718,81.1479,14.9545,76.3582
perf,"wip",mb32ic128ih13oc128oh13kh1n"wip",0.177209,0,1.93797,91.4408,2.10537,84.17
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):16.0098 avg(ms):17.0599
omp:4
perf,"wip",mb32ic128ih13oc128oh11kh3n"wip",1.1419,0,14.1063,80.9495,15.0331,75.9589
perf,"wip",mb32ic128ih13oc128oh13kh1n"wip",0.177209,0,1.93945,91.3708,2.12711,83.3097
tests:2 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0
total perf: min(ms):16.0458 avg(ms):17.1602
```
