### ISSUE TITLE
Incorrect results with convolution+addition+relu operation

### ISSUE THREAD

**Issue by nhkrishna** [intel/mkl-dnn#459]
Hi,

I have created custom network which contains the **conv-->sum-->relu** pattern. 
So i fused this pattern(conv+sum+relu) of layers using the MKLDNN post_ops API. 

I have observed incorrect results while performing conv+sum+relu operation. The reason could be sum operation gets the two different input formats in convolution+sum+ReLU fusion. One input was **nChw8c** from the convolution operation and other input was in the **nchw** format for sum operation in convolution+sum+ReLU fusion.

 If i use sum primitive explicitly, then it handles the different input data formats correctly. But If i use conv+sum+relu fusion, sum operation not handling the different input data formats. 

Could anyone please look into this issue?

Thanks,
Hari

**Comment by emfomenk** [comment]
Hi @nhkrishna,

A sum post-op doesn't support the cases when the resulting dst layout doesn't match the original one. See the documentation note [here](https://intel.github.io/mkl-dnn/group__c__api__attributes__post__ops.html#ga172931a133db5d1a3605495ad877d364).

I don't think the sum post-op would support that kind of mismatch any time soon:
1. because the API as is doesn't allow to pass an extra layout (**nchw** in your case), and 
2. because it might be not beneficial in terms of performance to have such a fusion (or it would be really hard to implement such kind of convolution kernel).

**Comment by nhkrishna** [comment]
Thanks for your reply @emfomenk .

If i do the reorder to sum data as the output it data, then i got the correct results.
