### ISSUE TITLE
Q: Question on OpenMP dependency

### ISSUE THREAD

**Issue by ilia-cher** [intel/mkl-dnn#463]
Hi, we're thinking about removing dependency on OpenMP in our project (not linking with OMP and instead using TBB or native thread pool, as an option), and want to try MKL-DNN compiled with TBB support.

I noticed that there're some places where `pragma omp` is used (?), e.g.

```
define PRAGMA_OMP_SIMD(...) PRAGMA_MACRO(CHAIN2(omp, simd __VA_ARGS__))
```

Also found this comment in OpenMP.cmake:

```
# Compilation happens with OpenMP to enable `#pragma omp simd`
# but during linkage OpenMP dependency should be avoided
```

And in Threading.cmake:

```
# While MKL-DNN defaults to OpenMP (if _OPENMP is defined) without CMake, here
# we default to sequential threading and let OpenMP.cmake and TBB.cmake to
# figure things out. This is especially important because OpenMP is used both
# for threading and vectorization via #pragma omp simd
```

Not sure what implications are there for the TBB-based MKL-DNN build? Does it still need OpenMP and what would happen if we don't compile with OMP support and don't link with OpenMP library?

Also, related question - is there a way or is it possible to add a CMake option to build a sequential version of MKL-DNN?

Thank you!

**Comment by ilia-cher** [comment]
(Re. second question - I found an option `MKLDNN_THREADING=SEQ` (undocumented?))

**Comment by emfomenk** [comment]
Hi @ilia-cher,

Yeah, `MKLDNN_THREADING=SEQ` is undocumented but proper way to build Intel MKL-DNN sequentially :)

Regarding OMP dependency with TBB. In order to make `#pragma omp simd` work you need to compile the code with OpenMP support (i.e. pass `-fopenmp` **compiler** flag). This by itself doesn't add a dependency on OpenMP RT, as opposite to the case when you use `#pragma omp parallel`. So if during the linkage a user doesn't pass `-fopenmp` or `-lgomp`/`-liomp5`, the library would not depend on OpenMP. See an example [1] below.

Since Intel MKL-DNN actively uses `#pragma omp simd` for vectorization, we try to use `-fopenmp` during compilation even if the library is built with TBB threading.

However, there are a few pitfalls about using TBB in Intel MKL-DNN:
- Currently only inference is optimized for TBB. Backward pass would work as well, but there would be limitted parallelization, which would lead to not as good performance as OpenMP on the system with high core count. We have some prototype to improve TBB performance for training, but haven't had a chance to promote it yet;
- If you want to build the library with TBB, you either should build with **full** Intel MKL binary dependency or without Intel MKL at all. You **cannot** use Intel MKL ML small binaries, because we only ship versions with GNU or Intel OpenMPs.

So it is fine to try Intel MKL-DNN with TBB, but please expect some performance impact, especially on backward pass.

BTW, may I know the reason you consider switching away from OpenMP?

[1]. Building Intel MKL-DNN w/ TBB (and compiling with -fopenmp to use vectorization)
``` bash
$ cmake -DMKLDNN_THREADING=TBB -DMKLDNN_USE_MKL=NONE && make VERBOSE=1 -j install
# lots of output like:
# g++  ... -DMKLDNN_THR=MKLDNN_THR_TBB ...  -fopenmp ... -c jit_avx512_core_x8s8s32x_convolution.cpp
# lots of output, and build completed

$ ldd libmkldnn.so.0.95.0.0
        linux-vdso.so.1 =>  (0x00007ffd1f3a5000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f54352c2000)
        libtbb.so.2 => /lib64/libtbb.so.2 (0x00007f543508c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5434e88000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5434b7f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f543487c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5434666000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f54342a5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f54365d9000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f543409c000)
# note, there is no libgomp.so (GNU OpenMP RT) in the dependencies
```

**Comment by ilia-cher** [comment]
Thanks for the detailed answer!

One issue with OpenMP is that it seems to not work very well when application does some other kind of threading, e.g. it doesn't guarantee a fixed number of threads in the process (there's OMP_THREAD_LIMIT but it will crash the program if it goes over it). In particular, libgomp seems to create a new thread pool for each newly created std::thread, so we were thinking about using TBB (or native thread pool, but in this case we can't parallelize within MKL/MKL-DNN).

**Comment by emfomenk** [comment]
Yeah, composability with other threadings is definitely a weak point of OpenMP.
However, there are still some workarounds that might alleviate the problem. For instance if you use Intel OpenMP runtime in most of the cases setting `KMP_BLOCKTIME=0` might solve the issue of oversubscribed system (in the assumption that you still don't run simultaneously OpenMP-enabled code with something else). But I agree that TBB or even application's native thread-pool (if Intel MKL-DNN supports it) might be a better solution.

Please let us know your findings once you try Intel MKL-DNN with TBB :)

**Comment by ilia-cher** [comment]
thanks!
