### ISSUE TITLE
How to retreive the data format from a memory descriptor ?

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#470]
How can I get the mkldnn_format_tag_t value from a memory descriptor?

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

According to the [RFC: Intel(R) MKL-DNN API 1.0](https://github.com/intel/mkl-dnn/pull/384) there is no more possible to retrieve the tag from the memory descriptor. The tags are only used to specify the memory descriptor format, but the actual information is stored in `md.format_desc.{blocking,other..}`.
See the last but one paragraph in section [5. Memory descriptor rework](https://github.com/intel/mkl-dnn/tree/rfc-api-changes-v1.0/doc/rfc/api-v1.0#5-memory-descriptor-rework) of the RFC.

**The rational**: there might be different tags correspond to the same memory format. Also a user might want to initialize memory descriptor simply by specifying the strides (i.e. no tags are used at all).

**Comment by dev2y** [comment]
I too run into same issue. mem::desc().data.format doesn't work any more. We are updating to MKLDNN 1.0 and we check formats and decide to reorder or not. format_kind is different than format_tag. 

auto temp = conv1_prim_desc.weights_desc().data.format_kind; 

@emfomenk looks like we should compare memory_desc instead of memory format.

I am wondering why format is hidden from memory desc in 1.0. I think we still want to know the memory formats. Especially for Convolution primitive. Any plans to make format_tag accessible from memory description?

    /* create a convolution */
    auto conv1_desc = convolution_forward::desc(prop_kind::forward_inference,
            algorithm::convolution_direct, conv1_src_md, conv1_weights_md, conv1_bias_md,
            conv1_dst_md, conv1_strides, conv1_padding, conv1_padding,
            padding_kind::zero);
    auto conv1_prim_desc = convolution_forward::primitive_desc(conv1_desc, eng);
    if (conv1_prim_desc.src_desc() != user_src_memory.get_desc()) {
        conv1_src_memory = memory(conv1_prim_desc.src_desc(), eng);
        net.push_back(reorder(user_src_memory, conv1_src_memory));
        net_args.push_back({ { MKLDNN_ARG_FROM, user_src_memory },
                { MKLDNN_ARG_TO, conv1_src_memory } });
    }

**Comment by zeno40** [comment]
I'm also wondering if the data format a primtive like convolution choose is agnostic to the batch size that's been used in the memory descriptors. If for a batch size of 1 the same data formatting is selected as for a batch size of 128? Just asking to be sure.

**Comment by emfomenk** [comment]
@dev2y, please go through the RFC link I gave above. It explains why memory format tags are fragile. The quite short answer is:
- tags do not allow to cover all the formats we have
- different tags my designate the same memory format (consider `nchw` and `oihw`)
- (vise versa) same tag might designate different memory formats (consider dense `nchw` and `nchw` with `stride_n = c*h*w+1`)
- user might want to create a memory w/o tags at all, i.e. by specifying directly the strides

To avoid these issues we allow users create a memory based on tag, but instead of using tag inside we rather keep the physical structure only. Recover the structure might require some knowledge.

If you need to understand whether a reorder is required or not you should use `memory::desc::operator ==` (see [this](https://github.com/intel/mkl-dnn/blob/b1371e3ae5e9139f5ea5d837c549a2bb9abe44e5/include/mkldnn.hpp#L1146-L1150)). If you want to understand in what format the memory is laid out, well... for the plain layout it is pretty straightforward: 

``` c++
auto is_plain = [](const memory::desc &md) {
    return true
        && md.data.format_kind == mkldnn_blocked // blocked format
        && md.data.format_desc.blocking.inner_nblks == 0; // no dimension blocking
};

auto is_nhwc = [](const memory::desc &md) {
    if (!is_plain(md)) return false;
    const auto &dims = md.data.dims;
    const auto &strides = md.data.format_desc.blocking;
    return true
        && strides[0] == dims[1]*dims[2]*dims[3] // stride_n = c * h * w
        && strides[1] == 1                       // stride_c = 1
        && strides[2] == dims[3]*dims[1]         // stride_h = w * c
        && strides[3] == dims[3];                // stride_w = c
};

auto md_nhwc = memory::desc({n, c, h, w}, f32, memory::nhwc);
auto md_nchw = memory::desc({n, c, h, w}, f32, memory::nchw);

assert(is_nhwc(md_nhwc));
assert(!is_nhwc(md_nchw));
```

**Comment by emfomenk** [comment]
@zeno40,

There are no guarantees the memory format desired for a convolution for the case `batch=1` is the same as the format for the *same* convolution with `batch=128`. Because from MKL-DNN stand point these would be different convolution and library would try to optimize them independently.

However, the way the library is implemented **now** for **CPU** it is highly unlikely that convolution would ask for different layouts if only batch size is changed (at least to the best of my knowledge).

But for **GPU** this is already not the case. Compare case [batch % 32 == 0](https://github.com/intel/mkl-dnn/blob/b1371e3ae5e9139f5ea5d837c549a2bb9abe44e5/src/ocl/jit_gen9_common_conv_kernel.hpp#L356) and [batch % 32 !=0](https://github.com/intel/mkl-dnn/blob/b1371e3ae5e9139f5ea5d837c549a2bb9abe44e5/src/ocl/jit_gen9_common_conv_kernel.hpp#L368). In first case you will get `NChw16n16c` format for data and for the second you'll get `nChw16c`.

There might be some day when we will have to do something similar on CPU as well. So the portable code **should not** assume the layout is not changed for different batch sizes if convolution is created with format `any`.

**Comment by zeno40** [comment]
Thanks for all the clarifications!

Now it's all clear for me.
