### ISSUE TITLE
reorder parameters

### ISSUE THREAD

**Issue by dev2y** [intel/mkl-dnn#472]
In 1,0, primitives are created without memory.

`auto conv1_prim_desc = convolution_forward::primitive_desc(conv1_desc, eng);
`

But Reorder still expects src and dst memories in reorder constructor and again pass them as arguments. Isn't it redundant?

```
    /* create reorders for data and weights if layout requested by
     * convolution is different from NCHW/OIHW */
    auto conv1_src_memory = user_src_memory;
    if (conv1_prim_desc.src_desc() != user_src_memory.get_desc()) {
        conv1_src_memory = memory(conv1_prim_desc.src_desc(), eng);
        net.push_back(reorder(user_src_memory, conv1_src_memory));
        net_args.push_back({ { MKLDNN_ARG_FROM, user_src_memory },
                { MKLDNN_ARG_TO, conv1_src_memory } });
    }

```

**Comment by dev2y** [comment]
creating new issue

**Comment by emfomenk** [comment]
Quick answer on the original question. The reorder has few constructors.
The main reorder constuctor is this one:
``` c++
reorder(const primitive_desc &pd): primitive(pd.get()) {}
```
You can find it [here](https://github.com/intel/mkl-dnn/blob/b1371e3ae5e9139f5ea5d837c549a2bb9abe44e5/include/mkldnn.hpp#L1342).

The proper way to create a `reorder::primitive_desc` is to call this constructor:
``` c++
        primitive_desc(const engine &src_engine, const memory::desc &src_md,
                const engine &dst_engine, const memory::desc &dst_md,
                const primitive_attr &aattr = primitive_attr());
```

[Link](https://github.com/intel/mkl-dnn/blob/b1371e3ae5e9139f5ea5d837c549a2bb9abe44e5/include/mkldnn.hpp#L1296-L1305).
It requires memory descs, engines, and attributes. You don't need to have memory objects.

But if that happens that you already have memory objects it might be *convenient* to create reorders based on them directly. That's why we have these extra constructors.

So the long story short, the ctors you mentioned are indeed redundant. And should be considered as the ones for users convenience.

I will into the bug in the corresponding thread #473.
