### ISSUE TITLE
confused with mkl-dnn format 

### ISSUE THREAD

**Issue by fengyuICT** [intel/mkl-dnn#475]
As we can see https://intel.github.io/mkl-dnn/understanding_memory_formats.html, the example include three formats(not include split channels), so my questions is mkl-dnn support use chwn or not, and why? since chwn is used as a format in neon. 
Another question is why not split nhwc's channels, something like that nhw8c?

**Comment by emfomenk** [comment]
Hi @fengyuICT,

Intel MKL-DNN supports `chwn` format just as any other plain memory format (i.e. no blocking and the memory is described with strides for each dimension). Moreover, the library has a dedicated memory format tag [`mkldnn_chwn`](https://github.com/intel/mkl-dnn/blob/v1.0-pc2/include/mkldnn_types.h#L300), that allows you to create memory in the `CHWN` format like that:
``` c++
  mkldnn_memory_desc_t md;
  mkldnn_dims_t dims = {N, C, H, W};

  // v0.x
  mkldnn_memory_desc_init(&md, 4, dims, mkldnn_f32, mkldnn_chwn);

  // v1.x using format tag
  mkldnn_memory_desc_init_by_tag(&md, 4, dims, mkldnn_f32, mkldnn_chwn);

  // v1.x using strides for plain format
  mkldnn_dims_t strides = {1, H*W*N, W*N, N}
  mkldnn_memory_desc_init_by_strides(&md, 4, dims, mkldnn_f32, strides);
```

> Another question is why not split nhwc's channels, something like that nhw8c?

I am not sure I get the question.
Do you ask why don't we block channels by 8 the `nhwc` format, i.e. why don't we use `nhwC8c` format? Well, this is possible, however, for `nhwc` case we prefer directly go with this memory format since a lot of framework has it a default memory format. Hence supporting it directly will allow us to avoid unnecessary conversion of data between `nhwc <-> nhwC8c`.
Also, performance-wise `nChw8c` leads to better performance than `nhwC8c`, mostly because the latter has some issue with the cache locality.

**Comment by fengyuICT** [comment]
Thanks for you answering @emfomenk . Does any primitive use chwn, such as conv, pool ? I searched mkldnn code use grep command, and I'm not sure mkldnn use chwn or not?

**Comment by emfomenk** [comment]
For convolution (and other compute-bound primitives) we recommend users to allow the library defining the memory format for the inputs/outputs (using memory format `any`). See the corresponding documentation [page](https://intel.github.io/mkl-dnn/memory_format_propagation_cpp.html).

For memory-bandwidth-bound primitives, like pooling, relu and others we suggest users to pass whatever memory format they got from the previous layers. Typically these layers include convolutions, hence the memory format would be our internal one (sometimes referred as blocked, such as`nChw8c`). See the same documentation page.

However, it might happen that this pooling is the first one in the topology, hence the memory format is the a default one that is used by a user or framework. Typically the default formats are `nchw` or `nhwc`. For these formats we also have optimized memory-bandwidth-bound primitives. Alas, we don't have optimizations for `chwn` memory format, and the reference code will be used (which is functionally correct but rather slow).

**Comment by nathan-greeneltch-intel** [comment]
@fengyuICT  In the future, if you have a similar concern about format, you can check the tables in the primitive sections of the new MKL-DNN dev guide. For instance, the pooling primitive section is [here](https://intel.github.io/mkl-dnn/dev_guide_pooling.html)You can see the list of optimized formats (which does not include **chwn**).
