### ISSUE TITLE
Question about inner product primitive

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#484]
Hi,

When reading the documentation about inner product it states the memory formats it expects for 2D are:
source/weights/destination
NCHW / OIHW/NC 

As the destination is in NC format it gives a problem when using it as a sources for the convolution that follows.
The reorder fails because NC has only 2 dims and the reorder expects src and dst of the same dimensions not nc and nchw for example. How can I use the dst of the inner product as a source in a primitive like the convolution without working with wrong mem formats.
The convolution doesn't now in advance wich primitive it has as a source.
What about the blocked format in the inner procuct primtive? 

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

This is a very good question! Currently the only answer I have is that the `dst` should be re-thought as `nchw` memory with `h=w=1`. Since the output is always `nc` it should be more or less straightforward to do:

``` c++
memory_desc_t ip_dst_md;
memory_desc_t conv_src_md; // = ip_dst_md;
memory_desc_init(&conv_src_md,
    ndims = 4,
    dims = {ip_dst_md.dims[0], ip_dst_md.dims[1], 1, 1},
    f32, nchw);

memory conv_src_mem(
    conv_src_md, engine,
    ip_dst_mem.get_data_handle()); // use IP's data buffer
```

However, this code is of course not very portable / reliable. If we decide to change the memory format of the `dst` that IP uses the code above will become invalid.
To overcome this issue and allow users to write really portable code, we will have to add **reshape** auxiliary function which is slightly touched by the RFC for v1 [here](https://github.com/intel/mkl-dnn/blob/rfc-api-changes-v1.0/doc/rfc/api-v1.0/rfc_memory_desc.md#51-reshape-).

**Comment by zeno40** [comment]
Why doesn't the reorder primitive treats the nc format as ncwh/ncwh so it could do the operation to a blocked format without throwing an exception? Wouldn't this be a good solution?

**Comment by vpirogov** [comment]
It does not seem to be a bug, this is pretty much a design decision for inner product.

@zeno40, 

considering that the output of inner product by definition has 1x1 spatial the convolution on inner product output will be mathematically equivalent to inner product. So the convolution is probably not the best example. Is this the situation that you encounter in a model?
