### ISSUE TITLE
Question about Softmax primitive

### ISSUE THREAD

**Issue by zeno40** [intel/mkl-dnn#487]
Does the softmax primitive support blocked format or is it "limited" to nc/nchw?
I also don't fully understand the axis parameter. When you have a nc formatted input the axis value should be set to 1 for both fprop and bprop. In case of a nchw input it should be set to 3.
When does I have to use a axis value of 0?  

thanks

**Comment by emfomenk** [comment]
Hi @zeno40,

Please check the documentation for softmax [here](https://intel.github.io/mkl-dnn/dev_guide_softmax.html). It explains what `softmax_axis` is and what cases are optimized.

In general, softmax typically happen over channel (feature) dimension. Other dimensions are considered as batch. I've never met softmax for NCHW where H and W would not be 1. But still I would expect that the softmax itself should happen over C, so the `softmax_axis` should be 1 (channel is dim 1 here).

We have an optimized softmax even for `nChw8c/nChw16c` format, assuming that `h=w=1`. Again, this is mostly because we've never seen the case where that would not hold. Please let us know if you face with such a case.

Also regarding the optimizations, I think you should try the latest master or mnt branch, because we only recently did some of the optimizations, which might not be included in v0.18 or v0.19.

**Comment by zeno40** [comment]
Thanks for the response! 
I don't have a scenario where w=h=1 isn't the case.

**Comment by emfomenk** [comment]
Ok, that's good.
Then I think you should be good to go no matter what memory format you use (`nc`, `nchw`, `nhwc`, or `nChwBc`). In all these cases I would expect `softmax_axis = 1`, because `c` is logical dimension `1` (regardless of the actual physical memory format).

**Comment by zeno40** [comment]
thanks
