### ISSUE TITLE
How to force to use implicit GEMM 

### ISSUE THREAD

**Issue by WeiHao97** [intel/mkl-dnn#494]
Hi,
I am trying to measure the overhead of conv2d on image size (1080*1920) in pytorch. And I am trying to measure the  overhead for " implicit gemm" specifically. How ever pytorch chose "direct convolution" for my conv2d operation. I would like to know if there is a way to force the algorithm used to be  "implicit gemm"?
Thank you very much!

**Comment by emfomenk** [comment]
Hi @WeiHao97,

There are few ways of doing that.
1. Through the MKL-DNN API by using [mkldnn::primitive_desc::next_impl()](https://intel.github.io/mkl-dnn/structmkldnn_1_1primitive__desc.html#a92fa1a8b789ab757c2cf811a74e696ef). Basically, when you create conv primitive desc, you need to call `next_impl()`, until you meet gemm-based implementation:
``` c++
conv_pd = mkldnn::convolution_forward::primitive_desc(...);
while (std::string(conv_pd.impl_info_str()).find("gemm") == std::string::npos)
    conv_pd.next_impl();
```

2. Simpler solution. In `src/cpu/cpu_engine.cpp` comment out all non-gemm-based convolution implementations that occur before gemm-based. E.g. these [ones](https://github.com/intel/mkl-dnn/blob/rls-v0.20/src/cpu/cpu_engine.cpp#L110-L141). Then rebuild Intel MKL-DNN.

Please note, that these changes would also affect the surrounding layers and primitives, since gemm-based implementation uses default memory format `NCHW` rather than SIMD-aware one (e.g. `nChw16c` or `nChw8c`). So if want to measure only the convolution, it might make sense to use standalone benchmark as [benchdnn](https://github.com/intel/mkl-dnn/tree/rls-v0.20/tests/benchdnn) instead.

**Comment by WeiHao97** [comment]
Thank you!
