### ISSUE TITLE
MKL  library dependency

### ISSUE THREAD

**Issue by uu-praveeng** [intel/mkl-dnn#503]
Hi,

It appears that the latest release does not include the MKL libraries as a dependency . 
We were using few  APIs(vsAdd,vsMul) from the MKL library  for elementwise addition and elementwise multiplication. 
Could you let us know any APIs present in mkldnn to do the same ?
Are these APIs being merged into MKLDNN ?

Thank you,
Praveen.

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

Starting with Intel MKL-DNN v1.0 the library no more depends on Intel MKL. All the required implementations (mostly integer and floating point gemm) were ported directly to Intel MKL-DNN. So that's why we will stop publishing Intel MKL-ML small libraries here.

If you use Intel MKL functionality you can download it from one of the channels (see [this answer](https://github.com/intel/mkl-dnn/issues/206#issuecomment-377552655)).

`vsAdd, vsMul` are not in Intel MKL-DNN. We plan to add some generic tensor arithmetic primitives, and `+`/`*` would be there (*which might be an overkill, though, you simply want to add/multiply two vectors unrelated to Intel MKL-DNN memory objects*). But we don't have any timeline for that yet.

**Comment by emfomenk** [comment]
Close the issue since the question is answered.
Feel free to reopen or open a new one in case of additional questions.
