### ISSUE TITLE
Question on Eltwise primitive API

### ISSUE THREAD

**Issue by jczaja** [intel/mkl-dnn#504]
Hi,

Currently eltwise backward primitive is expecting src input eg. input signal as the one accepted into eltwise primitive. This makes eltwise backward to "recompute" eltwise forward primitive at least for some algorithms. This may have some performance penalty comparing to situation when we are just reusing output (dst) from eltwise primitive. I'm guessing that this is because not all algorithms of backward eltwise my utilize dst memory , hence having src memory seems to be safe choice. But I'm curious,

1) Why do backward eltwise is taking src as input not dst?
2) Is there a path where we could pass output of forward eltwise (dst) so it is consumed by eltwise backward ? (passing through workspace?)

**Comment by emfomenk** [comment]
Hi @jczaja,

This was conscious decision driven by simplifying the API.
For some particular eltwises you can compute `diff_src` based on `diff_dst`, and `dst`. For instance, if `elwise(x) = e^(-a*x)`, you can use `src` or `dst`, both work. However, if consider relu with non-zero negative slope it might appear that you have to `src`, since `dst` would not be enough:
```
dst = relu(src) = src if src > 0, else -src

-->

diff_src = bwd_relu(diff_dst, src) = diff_dst if src > 0, else -diff_dst
```
Here, `dst` cannot be used to pick the sign!

So we chose the universal formula that always works:
```
    diff_src <-- bwd_eltwise(diff_dst, src)
```

Even if we need to re-compute the `dst = fwd_eltwise(src)`, which is always possible. We haven't observed any significant performance implications caused by this decision.

**Comment by jczaja** [comment]
So there is no way to force mkl-dnn to utilize dst instead of src for eltwise_backward ? The reason I'm asking it just paddlepaddle is utilizing dst for all bwd activations, and We need to modify their computation graph to have src passed to backward of activation not dst.

**Comment by emfomenk** [comment]
Currently there is no way to do that with Intel MKL-DNN API.
I can see 2 workarounds:
1. Either rewrite the graph to pass `src` indeed
2. Or by having `dst` recompute `src` if this is possible (which is not always the case, alas).

If both approaches would not work, we can try to think about API accommodation. For instance, we can introduce new primitive descriptor attribute that would instruct eltwise primitive to use `dst` instead of `src` as an input on backward pass.

But in order to do that we would like to have a justification. Convenience is definitely a part of it. Maybe it also turns out that this will help performance as well (though we haven't seen that as I said above).

**Comment by jczaja** [comment]
Thanks very much @emfomenk
