### ISSUE TITLE
Inplace sum

### ISSUE THREAD

**Issue by adeleCou** [intel/mkl-dnn#505]
Hello,

I am working on reducing the memory used at the inference by mkldnn, and I noticed that there is no version of the sum inplace. Did I miss it ? Or would it be possible to add this possibility?

Thank you,

Adèle.

**Comment by emfomenk** [comment]
Hi @adeleCou,

Alas, in general case the in-place sum is not possible. Mainly, due to the different memory formats that inputs and output might have.

Intel MKL-DNN supports in-place sum under the following conditions:
1. Output buffer is the same as the buffer of the **first** input, i.e. `dst.handle == src[0].handle`
2. Output has the same physical memory format and data type as the **first** input, i.e. `dst.memory_desc = src[0].memory_desc`

If these conditions met, you can safely execute in-place sum.

Out of curiosity, you said you are working on reducing the memory footprint of Intel MKL-DNN. I am not sure if out-of-place sum significantly contributes to the memory consumption. Could you please share your analysis on memory consumption? For instance, some primitives might require extra internal buffers (called [scratchpad](https://intel.github.io/mkl-dnn/dev_guide_attributes_scratchpad.html)) to perform some reductions or other work. It might happen that such kind of buffers might consume more than one extra buffer caused by out-of-place sum.

**Comment by adeleCou** [comment]
Thank you @emfomenk for your quick answer, I will try it out.
As for the analysis part, I had a very naive approach. I have regularly additive connections inside my network and I just wondered if I could do it inplace, (and in my mind, in terms of memory used it would be like not having these connections anymore, as it could be inplace elementwise operations). I will do some experiments and let you know if it improved significantly my footprint!
I was also planning on working on the reuse of the memory allocated for previous operations but not used anymore. 
 As for the internal buffers, as I am not really an expert I will leave it for now!

**Comment by adeleCou** [comment]
Hi @emfomenk , just so you know, I had an important gain doing that!
I came down from 10Go to 3Go. You might be surprised by sizes this big, but it is because I am working in 3D (~200*200*200 inputs), so for my case it was very interesting to do inplace computations.

Thank you for your support!

**Comment by emfomenk** [comment]
Hi @adeleCou,

Glad to hear you get such good improvement!

Just in case, please note that Eltwise (ReLU and others) and Batch Normalization also support in-place computations.

**Comment by adeleCou** [comment]
Yes, that was already used, I think I will stop here for the memory optimization part.
Thank you!
