### ISSUE TITLE
Question about round mode in pooling

### ISSUE THREAD

**Issue by Sherry-Zhang** [intel/mkl-dnn#513]
Hi，the pooling primitvie in mkl-dnn do not support ceil round mode. But in caffe, pooling layer's default round mode is ceil, so I need to fix it in my project.
According to #325 , I tried to support ceil mode by changing padding size, it works well in maxpooling. But when algorithm kind is mkldnn::algorithm::pooling_avg_include_padding, changing padding size will change pooling size, so the output average value in the last row and last column will be wrong. How to fix it?

**Comment by emfomenk** [comment]
Hi @Sherry-Zhang,

I don't remember exactly the difference between Caffe's average pooling definition wrt to the cases when the window goes out of boundaries, but I recall the choice was rather peculiar.
In Intel MKL-DNN the formula for the denominator is:
``` cpp
auto denominator = (alg == alg_kind::pooling_avg_include_padding)
     ? KW * KH * KD
     : (id_end - id_start) * (ih_end - ih_start) * (iw_end - iw_start); // area of the exact intersection
     ...
     dst = dst / denominator;
```

I think there might be 2 choices:
- Sacrifice the accuracy on the right and bottom boundaries and hope that would not affect the convergence / inference much.
This, I think what IntelCaffe did when integrated Intel MKL-DNN, i.e. they slightly diverged from the original Caffe definition of average pooling: check for `PoolingParameter_RoundMode_CEIL` in [BVLC Caffe Pooling](https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L91-L106) and [Intel Caffe Pooling](https://github.com/intel/caffe/blob/master/src/caffe/layers/pooling_layer.cpp).
- If you need absolute compatibility with CEIL mode of Caffe, then IIRC that should be sufficient to pad the data manually and switch to `alg_kind::pooling_avg_include_padding`. If you don't want to deal with left and top padding, you can only pad the bottom and right boundaries and use `alg_kind::pooling_avg_exclude_padding`.

The latter approach would be intrusive. Also you would have to reorder the data back in the native memory format (like `NCHW` or `NHWC`) to be able to manually pad the data. That might have performance implications. So I would probably suggest to go with the former approach...

**Comment by Sherry-Zhang** [comment]
@emfomenk It seems that there is no perfect solution. In engineering team, we use pre-trained models from algorithm team. Maybe these models are trained by different framework, we just transform and deploy them. So we hope to keep consistency of outputs. Diverged op definition is not expected. Anyway, thanks for your suggestion :)

**Comment by emfomenk** [comment]
Hi @Sherry-Zhang,

Actually, instead of explicitly putting zeros in the right and bottom sides it might be slightly better to rescale the resulting buffer by the appropriate number. I.e. knowing the difference in the denominators, once the result is obtained by Intel MKL-DNN pooling the boundary elements need to be multipled by the ratio of denominators.
The main obstacle here is that Intel MKL-DNN might use blocked memory format for the data, which might be not easy to understand. But since we typically use one partial one (nChw8c or nChw16c for f32, and nhwc for int8), the implementation can be done fairly easy.

If you think this might work for you I can help with this function.

More product level solution might be adding a new pooling algorithm kind, that would mimic Caffe ceil behavior. We are open for PR that adds this functionality (when if for inference only).

**Comment by vpirogov** [comment]
Considering that discussed behavior does not impact major modern frameworks we decided not to proceed with the implementation. We would welcome a pull request if you still see value in this feature.
