### ISSUE TITLE
convolution precision issue

### ISSUE THREAD

**Issue by carlushuang** [intel/mkl-dnn#522]
Hi deal mkl-dnn team.

I found that convolution forward precision (normalized rms error) is bigger than conv bwd_data, or conv bwd_filter.

I have a small piece of code here:
https://github.com/carlushuang/mkldnn_test/tree/conv_fwd_precision_issue/conv

I test with batch=2, channel=8192, width=height=4, filter_number=8, filter_size=3x3, padding=0,  unit stride (or stride = 2), no dilation, no group.

I write a [naive implementation](https://github.com/carlushuang/mkldnn_test/blob/conv_fwd_precision_issue/conv/naive_conv.h) with C code, and use the mkldnn output compare with naive implementation, use [normalized rms ](https://github.com/carlushuang/mkldnn_test/blob/conv_fwd_precision_issue/conv/conv.cpp#L90)to check if correct.

The result is, convolution fwd have bigger rms error.
```
 n  c  h  w  k  r  s  p  q  u  v dh dw oh ow
 2 8192  4  4  8  3  3  0  0  2  2  1  1  1  1 (0.000005271871)y (0.000000058035)y (0.000000000000)y
```
forward conv rms is 0.000005271871, back data is 0.000000058035, back weight is 0.000000000000. forward data is much bigger than my [1e-6](https://github.com/carlushuang/mkldnn_test/blob/conv_fwd_precision_issue/conv/conv.cpp#L90) threshould.

I double check the algorithm is "[mkldnn::algorithm::convolution_direct](https://github.com/carlushuang/mkldnn_test/blob/conv_fwd_precision_issue/conv/mkldnn_conv.h#L67)", propery is "mkldnn::prop_kind::forward", but wonder in this case mkl still use some other optimization?

In my use case, I would like to let mkl-dnn tobe golden output, to compare with some other handwrite kernel, so i realy need the precision is good.

I issued https://github.com/intel/mkl-dnn/issues/521, to ask if there is a fp64 mkldnn to work aound precision, but there is no

-----------------------------------------------------------------------------
### Environment
* CPU: Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz
   flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d

* OS version: ubuntu 16.04.1
* Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
* mkl: /opt/intel/mkl, INTEL_MKL_VERSION = 20190004
* mkl-dnn: v0.20 (d89bf4babd7)

**Comment by rsdubtso** [comment]
There are many potential reasons why there may be a difference in the results:
- The compiler may have decided not to use FMAs (I think on your machine passing `-mtune=native` should enable them).
- The order of operations is different. Compiler may reorder loops, etc.

In general one should not expect to get bitwise identical results from two different implementations unless the input data is prepared in a special way (see how benchdnn fills the data so that all intermediate results are exact in f32; but even benchdnn approach has its limitations).

**Comment by emfomenk** [comment]
Hi @carlushuang,

I agree with @rsdubtso the different algorithms (or even different implementations of the same algorithm) might give different results. And it is really hard to say which one is closer the **_true_** result (i.e. computed with infinite precision).
- For instance, Intel MKL-DNN and Intel MKL will most likely use FMA on your hardware. And FMA in general is more accurate than MUL and ADD being executed separately. GCC might not be able to generate FMA for the reference code you wrote, have the result would be different with Intel MKL-DNN. And in some sense Intel MKL-DNN might be more accurate (due to FMA).

For more details see pytorch/pytorch#23042 issue and, in particular, this [comment](https://github.com/pytorch/pytorch/issues/23042#issuecomment-513419634).

For the case you mentioned it is worth noting, that the accumulation chain for forward is much longer than backward by data and backward by weights.

| Direction | Accumulation chain | Order of integer data to avoid rounding issues |
| -- | -- | -- |
| FWD | c * r * s ~= 2^17 | 2^3 |
| BWD_D | k * r * s ~= 2^7 | 2^8 |
| BWD_W | n * h * w ~= 2^5 | 2^9 |

Rounding issues happen because floating point number have limited mantissa width. Fp32 has 23 bit mantissa. That means if you want to get precise answer for expression:
```
sum(i = 0 .. 2^k) { a_i * b_i }
```
where `a_i` and `b_i` are integers you need to make `0 <= |a_i| <= 2^((23-k)/2)` and same for `b_i`.

That's how I obtained the last column of the table.
Once I applied the patch [1] the difference became zero for all three directions:
``` bash
$ ./conv.exe
 n  c  h  w  k  r  s  p  q  u  v dh dw oh ow
 2 8192  4  4  8  3  3  0  0  2  2  1  1  1  1 (0.000000000000)y (0.000000000000)y (0.000000000000)y
```

--- 

[1] `git diff -- conv.cpp`:

``` patch
diff --git a/conv/conv.cpp b/conv/conv.cpp
index 41fd113..8cd266b 100644
--- a/conv/conv.cpp
+++ b/conv/conv.cpp
@@ -73,7 +73,7 @@ void rand_vector(float * vec, size_t num){
     static size_t inited=0;
     size_t i;
     if(!inited){ inited = 1; srand (time(NULL));}
-    for(i=0;i<num;i++) vec[i] = ((float)(rand()%1000))/1000.0f;
+    for(i=0;i<num;i++) vec[i] = ((float)(rand()%8)); // /64.f;
 }
 size_t valid_vector(float *lhs, float *rhs, size_t num, float delta=0.02){
     size_t i;
```

**Comment by carlushuang** [comment]
thanks @rsdubtso for your kindly reply and thanks @emfomenk for the details about mantissa overflow consideration.

One thing I want to make sure is, the reason for use integer not float to do FMA while testing (e.g, use 0.001-0.999 in above case) is that, float number will still loss accuracy even when doing multiplication, and the loss will accumulate c*r*s(fwd), am I right?

**Comment by emfomenk** [comment]
Hi @carlushuang,

Pure integers allow using only higher bits of the mantissa in the floating point number representation. That in turn, allows avoiding rounding issues. Instead of using integers you also can use the rationals with `2^n` denominator. 
On contrary, the rationals like `1/10` cannot be exactly represented in floating point (since radix/base is `2`), and that will lead to rounding issues during operations pretty quickly.
See example below.

``` c
#include <stdio.h>

void check(float x, int multiplier, float exact) {
    float sum = 0;
    for (int i = 0; i < multiplier; ++i)
        sum += x;
    printf("Summing %14f %d times gives %e error\n", x, multiplier, sum - exact);
}

int main() {
    check(1.f,    10, 10.f   ); // OK, integer
    check(1.f/16, 10, 10.f/16); // OK, exactly representable number,
                                // since denominator is power of 2

    check(1.f/10, 10, 1.f    ); // FAIL, 1/10 cannot be exactly represented
                                // in floating point number. Hence, all mantissa
                                // bits will be used and during addition
                                // the rounding issues will happen.

    return 0;
}
```
``` bash
$ gcc -O0 tmp01.c && ./a.out
Summing       1.000000 10 times gives 0.000000e+00 error
Summing       0.062500 10 times gives 0.000000e+00 error
Summing       0.100000 10 times gives 1.192093e-07 error
```
