### ISSUE TITLE
Feature Request: Indexing into arbitrary MKL-DNN memory

### ISSUE THREAD

**Issue by CaoZhongZ** [intel/mkl-dnn#556]
Can we have some API to index arbitrary MKL-DNN memory as normal array, like those convenient helpers inside memory_desc_wrapper?

**Comment by rsdubtso** [comment]
Can you please share how would you use this functionality if provided? It is expected to be on the order of 1000x slower than traditional array indexing. It is often faster to reorder data to a known format like NHWC.

**Comment by CaoZhongZ** [comment]
I agree. The performance would be bad if we just index into it. However we are in a dilemma about this issue. Think about a scenario there are many references to a MKL-DNN memory based tensor, normally we can't just reorder the content to other format and substitute it because we don't track all the references.

For example, people might just wrote a[1] = something, we turned a into another MKL-DNN memory, all other references won't know about it.

**Comment by rsdubtso** [comment]
Do I understand you correctly that the use model is not to apply this functions to whole tensor operations, but to user-side indexing operations? If yes, can you reorder lazily? Like use the MKL-DNN memory as a shadow buffer which gets reordered from and invalidated if user performs any indexing operation? This will have its own problems, of course: it would be a very wasteful operation if user just touches a single element...

**Comment by CaoZhongZ** [comment]
You are right. Lazy is a nice thing if we could pull it off. But in PyTorch there is no way we could do lazy indexing and viewing. They have schema strictly regulate op's behavior, like when you view, you can't make new copy, because many tensor users referenced original tensor and the view must reference the original one, any change must spread original uses as well. The storage underlying a tensor has no virtual function we could hook.

MKL-DNN 1.0 API exposed all the stride and block information needed in descriptor, I thought it might be possible to index all the kinds of tensor. Maybe I was wrong.

**Comment by emfomenk** [comment]
I agree with @rsdubtso that we need to identify all the operations you would like to perform assuming we provide this functionality.
Generally, there are 2 main pitfalls with such function:
1. (functional) There are formats for which the indexing function simply does not exist. For instance:
    - Int8 weights with compensation, cause not only weights are kept, but also some characteristics (like sum over rows), so changing value should change some others as well 
    - F32 winograd weights, cause tensor is kept in Winograd domain -- no one can access a single element in time (real) domain
  
  - In theory this can be work-arounded if we provide setter and getter function instead of the indexing function. But this might be costly in terms of the implementation and performance (see 2).
2. (performance) For performance reasons it is crucial to process the tensors in the **right** order. If we provide the indexing function `off(n,c,h,w)` and someone will have generic code like this [1] the performance would be bad even for a tensor in NCHW format (because of an overhead of `off()` function) and would be unspeakably awful for a tensor in NHWC format (because of an overhead of `off()` function and the fact that tensor is traversed in **wrong** order).

So from my naive point of view the only usefulness from this function would be debugging purposes (i.e. quick check what value is located at point `(n,c,h,w)`).

But what @CaoZhongZ described sounds more like we need to provide view (and we actually do!) for people to use. It **wouldn't** help writing the values directly, but might help with running other DNNL primitives on the viewed area. For actual writing a value, I don't see any other option other than reordering data back to the native PyTorch memory format. 

(Completely) alternative solution would be to switch to native (read NHWC) memory formats. In this case there would not be any need in fragile indexing function.

[1].
``` c++
for (n in N)
for (c in C)
for (h in H)
for (w in W)
    x[off(n,c,h,w)] += 1;
```

**Comment by CaoZhongZ** [comment]
OK, you are suggesting NHWC is a way out, that's means DNNL will probably have a decent performance for that format? I'm going to check the readiness of NHWC in PyTorch JIT.

**Comment by vpirogov** [comment]
@CaoZhongZ, we are considering optimizing functionality for NHWC activations to simplify integration. There's no solid plan for that yet though.

**Comment by vpirogov** [comment]
Even with fully optimized convolutions for plain activations performance will still be materially lower than with blocked formats. So you need to take this into account when making integration decisions and inform maintainers about the consequences.

**Comment by CaoZhongZ** [comment]
Understood. We certainly want the best out of our platform. It's for the cast when there were really no better options.
