### ISSUE TITLE
Feature Request: Custom allocator for engine

### ISSUE THREAD

**Issue by pinzhenx** [intel/mkl-dnn#565]
Could we specify a custom allocator for engine memory creation?

**Comment by emfomenk** [comment]
Hi @pinzhenx,

Could you please elaborate on the use case you have in mind?
Do you want engine to use provided allocator for memory object allocations only or for all allocations (including the generated code and some read-only internal buffers the primitives might use)?

Currently, DNNL has the following options to control buffer allocations:
1. When a user creates DNNL memory object using
[`dnnl_memory_create(dnnl_memory_t *memory, const dnnl_memory_desc_t *md, dnnl_engine_t engine, void *handle)`](https://intel.github.io/mkl-dnn/group__c__api__memory.html#ga52a9246bd7f4e498b08d61e75e689a0c),
    where the handle can be:
    - A pointer to already allocated buffer, in which case DNNL doesn't allocate anything on its own
    - Special value `DNNL_MEMORY_ALLOCATE`, which says DNNL to allocate buffer (using system allocator)
    - Special value `DNNL_MEMORY_NONE`, which says to not attach any real buffer for created memory (the buffer should be attached later)
2. Primitives might also allocate some additional buffer required for computations. This buffer is called a [scratchpad](https://intel.github.io/mkl-dnn/dev_guide_attributes_scratchpad.html).
    - By default, the allocations happens at primitive creation and is opaque for users.
    - But if users want to control this memory allocation as well, they should set a special attribute:
     [`attr.set_scratchpad_mode(dnnl::scratchpad_mode::user)`](https://intel.github.io/mkl-dnn/dev_guide_attributes_scratchpad.html)
     and provide the corresponding memory at the execution time.

So the long story short, currently there is a mechanism that allows users to control all allocations for DNNL memory objects. Even though this mechanism might be less convenient than just a custom memory allocator attached to an engine....

**Comment by pinzhenx** [comment]
@emfomenk Thanks for your reply.
Firstly, I want to make the most of `DNNL_MEMORY_ALLOCATE` letting DNNL manage the **memory object**, meanwhile, hook the memory allocator instead of std malloc.
And then the next step, I also want to be able to hook all of memory allocations in the DNNL, but that's not an immediate requirement for now.

**Comment by emfomenk** [comment]
Thanks!

So do I understand you correctly, that most likely it is sufficient to provide an allocator for memory objects only? Eventually, it might be good to control all the memory, but it is not that important (compared to controlling the allocation for the memory objects).

Please also note, that memory allocated for the code generation must be changed from RW to RX at run-time. On systems with SELinux it might be important to directly allocate such memory with `mmap`, rather than with regular `malloc`. So, library-wise common allocator might be not a trivial thing...

For early experiment I can point you where the memory allocation happens in the library (on CPU):
1. Buffer allocation for DNNL memory object happens [here](https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_memory_storage.hpp#L40). Deallocation: [here](https://github.com/intel/mkl-dnn/blob/master/src/cpu/cpu_memory_storage.hpp#L58).
2. Buffer allocation for the scratchpad: [here](https://github.com/intel/mkl-dnn/blob/master/src/common/scratchpad.cpp#L54). Assuming the library does scratchpad allocations.
3. Library-wise all allocation happens through [`malloc/free`](https://github.com/intel/mkl-dnn/blob/master/src/common/utils.cpp#L84).

So if you want to try your idea, you may try replacing the calls to `malloc` in 1. and 2. with the call to a user defined allocator.

**Comment by pinzhenx** [comment]
@emfomenk That's exactly what I mean. I will give them a try. Thanks.
And that would be great if there's an API to control it.
