### ISSUE TITLE
Releases aren't sequential: 1.0.4 is made after 1.1.1

### ISSUE THREAD

**Issue by yurivict** [intel/mkl-dnn#580]

**Comment by yurivict** [comment]
Also ```git describe``` shows that 1.1 was the last release.

**Comment by rsdubtso** [comment]
Hi Yuri, can you please provide more info? 1.0.4 and 1.1.1 are bugfix releases to the 1.0 and 1.1 release branches respectively. They are not expected to be made in any particular order.

**Comment by vpirogov** [comment]
`git describe` information does not reflect the order of releases for this project. Here's the branching scheme that we use:
* `master` is used for ongoing development for stable major version (v1 now). No releases are done from the master.
* `mnt-vX` is for support of previous major version (v0 now). No releases are done from `mnt-vX` branches either.
* `rls-vX.Y` branch is created for each minor release at code freeze. The release candidate, vX.Y release, and vX.Y.Z patch releases are done from this branch.

With that `git describe HEAD` points to the latest release candidate, instead of the latest release.

Hope this helps. Feel free to reopen or create new question if you have further question about releases and branches.
