### ISSUE TITLE
Can the input or output shape influence the format or memory size of weights ?

### ISSUE THREAD

**Issue by i8run** [intel/mkl-dnn#584]
Hi,

I have a question about the memory size in dnnl.

When I create an operation such as convolution, I can set the memory format of input, output and weight to `any`. After creating the operation's primitive descriptor,  we can get the optimized/blocked memory format and the real memory size operation will be used.

There's a situation that, maybe the input size will change when doing inference. So we should recreate the primitives and the input && output must be reallocated if the previous memory is not enough. (We handle the memory by ourselves.) **But I'm confusing about the weight memory format and size. Do them change and need to resize** ?

I have read some codes about the convolution. I saw there're some format tag, such as `wei_tag`, `dat_tag` and so on.

1. It seems that the primitive will return fixed format determined by the implementation(jit_avx2_conv, jit_avx512_bf16_conv, gemm_conv...) whatever the input size. Am I right?
2. If the weight format is fixed, does it mean the relevant memory size will be fixed too?

Thanks very much.

**Comment by emfomenk** [comment]
Hi @i8run,

Thanks for the great question!

> There's a situation that, maybe the input size will change when doing inference. So we should recreate the primitives and the input && output must be reallocated if the previous memory is not enough. **But I'm confusing about the weight memory format and size. Do them change and need to resize?**

Alas, DNNL doesn't guarantee you that the weights format would stay the same in the case of changed input shapes. For instance, on GPU we have completely different formats depending on the number of the input images (so if batch is 1 and 16 the weights format most likely will be very different). These different formats might also have different size requirements:
- Say, `oIhw16i`, where only one dimension is blocked by 16, will have the size that is multiple of 16;
- But `OIhw16i16o`, where two dimensions are blocked by 16, will have the size that is multiple of 256;

For CPU the situation is a little bit better. **Typically** you would not get different weight formats depending on the input shape, but this is not an absolute. For instance, if you use algorithm kind `auto` depending on the minibatch DNNL might dispatch either Winograd or direct implementation. These cases lead to completely different weights (and their sizes).

> It seems that the primitive will return fixed format determined by the implementation(jit_avx2_conv, jit_avx512_bf16_conv, gemm_conv...) whatever the input size. Am I right?

You are partially right. The implementations you mentioned use single approach no matter what the sizes are. However, there are other implementation that cover multiple approaches at a time. They may choose different flags depending on some parameters. Also, what is more important, keep in mind that once you change the parameters the **different** implementation can be picked.

> If the weight format is fixed, does it mean the relevant memory size will be fixed too?

If the weight format is fixed and the shape is fixed too, than the size would stay as is. That's because the size is a function of the memory format and the shape.

---

Having said that, I want to mention that we got similar complain from PyTorch integration team. Essentially they want us to pick the weight format independently from the input/output shapes.
We are still thinking on how we can do that in DNNL (both in terms of API and in terms of correctness / performance guarantees). So, your input on the request is very welcome!
In particular, it is interesting what your expectations are on the performance: how much performance you will tolerate until agree to change the implementation so that it is ready for different weights formats.

**Comment by i8run** [comment]
Thanks your detail information @emfomenk . 

Another question is,

Is there any method supporting to get the format without creating whole layers primitive ?

**Comment by rsdubtso** [comment]
Creating a primitive descriptor should be sufficient. It then can be queried for memory descriptors of the source, destination, etc.

**Comment by emfomenk** [comment]
@i8run,

So is oK for you to re-reorder the weights if a change of input image would change the format of the weights?

**Comment by i8run** [comment]
Thanks @rsdubtso . 

@emfomenk , I have no any other methods. One way I think is two phase. First phase is iterating the model/network and getting the format. Second phase is initializing the model with the format although the performance is not the best. But it seems too complicated.

I will reorder the weights when input changes.
