### ISSUE TITLE
the ref_convolution.cl implementation not aligned to the mkl-dnn dev guide

### ISSUE THREAD

**Issue by joye** [intel/mkl-dnn#587]
https://github.com/intel/mkl-dnn/blob/master/src/ocl/ref_convolution.cl#L46
```
            const int id = od * SD - PD + kd * (1 + DD);
            const int ih = oh * SH - PH + kh * (1 + DH);
            const int iw = ow * SW - PW + kw * (1 + DW);
```

this implementation I think has some problem;  and also not aligned to 
[http://intel.github.io/mkl-dnn/dev_guide_convolution.html]

![a](https://user-images.githubusercontent.com/1277051/68263537-377de480-0081-11ea-9af6-67d11b9c2e1f.png)

And I think the formula in the dev guide also is wrong.

I think the formula should be 
```
            const int id = od * SD - PD + kd * DD;
            const int ih = oh * SH - PH + kh * DH;
            const int iw = ow * SW - PW + kw * DW;
```
please help check this issue. Thanks!

**Comment by emfomenk** [comment]
Hi @joye,

Thanks the report!
Actually the problem is in the documentation, and not in the source code. In DNNL we use the convention `dilation = 0` for regular convolution. Hence the formula in users guide should be:
```
dst(..., oh, ...) = ... src(..., oh + kh * (DH + 1) - PH_0, ...)
```

Please note, that other libraries or frameworks may use `dilation = 1` for regular convolution, e.g. this is the case for [PyTorch](https://pytorch.org/docs/stable/nn.html#conv1d).

**Comment by joye** [comment]
Thanks for explanation, so the dilation in Pytorch or Tensorflow models will be dilation-1 in DNNL? If this is true, can close this question.

**Comment by emfomenk** [comment]
Hi @joye,

> Thanks for explanation, so the dilation in Pytorch or Tensorflow models will be dilation-1 in DNNL?

Yes, that's correct.

I will leave the question open till we promote the fix to the documentation.
Thanks for noting the issue!
