### ISSUE TITLE
Question: Can I use the `reserved ` field inside desc?

### ISSUE THREAD

**Issue by pinzhenx** [intel/mkl-dnn#601]
I'd like to extend the functionality of memory desc to store some info, about several bytes. Can I use the `reserved` for that purpose? I know that one day this might come into conflict with DNNL's design, but for the short term, am I supposed to use these 200 bytes from high address (`reserved[199]`) or from low address (`reserved[0]`)?

**Comment by emfomenk** [comment]
Hi @pinzhenx,

Could you please share some insights on what you are trying to achieve?

In general, the reserved areas are not designed to store additional information, as the library can (in theory) override it with `0` during the initialization. It also might break the comparison function, as it is unclear if the same memory descriptors with only difference in un-interpret-able reserved should be treated as the same or not (*currently it would be treated as the same*).

Leaving all these cautions aside, I don't see any technical problems though -- e.g, if you want to do some quick experiment or so. Please find my comments on the approach below.

---

I see the `reserved[200]` belongs to the `dnnl_rnn_packed_desc_t` structure, that is a part of the union:
``` cpp
 937 typedef struct {
 ...
 970     /// Memory format kind.
 971     dnnl_format_kind_t format_kind;
 972     union {
 975         dnnl_blocking_desc_t blocking;
 977         dnnl_wino_desc_t wino_desc;
 979         dnnl_rnn_packed_desc_t rnn_packed_desc; // <-- part of
 981     } format_desc;                              //     this union
 982
 983     dnnl_memory_extra_desc_t extra;
 984 } dnnl_memory_desc_t;
```

This mean that depending on the `format_kind` the memory descriptor can not use `rnn_packed_desc` but, say, `blocking` descriptor.

However, `dnnl_memory_extra_desc_t` field is always available, which also has `char reserved[64]`:
``` cpp
 920 /// Description of extra information stored in memory
 921 typedef struct {
 922     /// The flags contain arbitrary extra information, such as compensation.
 923     /// @sa dnnl_memory_extra_flags_t
 924     uint64_t flags;
 925     /// Compensation mask
 926     int compensation_mask;
 927     /// Scale applied to the data
 928     float scale_adjust;
 929     /// For future backwards compatibility
 930     char reserved[64];
 931 } dnnl_memory_extra_desc_t;
```

We currently don't use either reserved bits, but the plan is that if we need something, we will add a field and shrink the reserved buffer. Hence the safest way would be to use something like:
``` cpp
size_t required_size = 2; // e.g. you need 2 bytes of space
size_t reserved_size = sizeof( ((dnnl_memory_extra_desc_t *)0)->reserved );
assert(reserved_size >= required_size);
size_t offset = reserved_size - required_size;
md.extra.reserved[offset] = (uint16_t)data;
```

I checked the way we compare memory descriptors -- we check field by field, so even if there would be some unknown information in reserved area of `extra` field we will ignore that. This may be a desired or not desired behavior for you. Please pay attention to that.

Also, please note, that `init_memory_desc()` or similar functions first zero the resulting memory descriptor. So, be careful to not lose the information. 

Apart from that I don't see why this idea would not work.

Needless to say, I don't recommend doing that, though. 😅

**Comment by pinzhenx** [comment]
Hi @emfomenk 

Thanks for your guidance. What I'm trying to do is to hide the difference of grouped weights from the framework, i.e., not let the framework perceive the change in weight dimensions.

From the perspective of DNNL, a grouped 4d weights is basically a plain 5d memory. But if I got a 5d memory, how can I get this 'grouped' info back?

So now I need some extra info, under current tag-free design, to indicate if a memory is grouped or not.

**Comment by emfomenk** [comment]
Hi @pinzhenx,

Thanks for the explanation! Though, I am still slightly confused: from the memory organization perspective (read _memory format_) there is no difference between regular 5D tensor and 4D weights for grouped convolution (which leads to the 5D tensor as well). So, the only place where you need to know whether a tensor represents 4D weights w/ groups or 5D activations is typically somewhere closer to the convolution operation itself. But in this case you already know what kind of the tensor it is, since you work on the operation (sorry for the pun).

I guess, you use some form of an abstraction (to simplify the programming DNNL), but I am not sure I understand why exactly you need that / what problem you are solving. I would appreciate if you elaborate on this more.

> From the perspective of DNNL, a grouped 4d weights is basically a plain 5d memory. But if I got a 5d memory, how can I get this 'grouped' info back?

Our idea was that the memory descriptor and memory format don't have any semantics attached to the memory itself. Their sole purpose is to describe physical layout in memory address space. We hoped that all the semantics would be carried by the upper level application.
So, my answer on your question is:
1. You either look at the convolution configuration for which these weights come from and derive whether it is grouped 4D weights or proper 5D weights;
2. You have your own tensor meta data that **encapsulates** DNNL memory desciptor, but carries any additional required information, such as the purpose of the tensors (e.g. `weights` or `activations`), the number of logical dimensions (if your framework consider groups as not an additional dimension) and whatnot:
    ``` cpp
    my_fwk_tensor_descriptor_t {
        tensor_type type; // activations or weights
        int logical_dims; // 4 even for grouped weights, if FWK treats
                          // weights like [ G * OC / G, IC / G, KH, KW ]
        dnnl_memory_desc_t dnnl_md; // data for DNNL
    };
    ```
