### ISSUE TITLE
No improvement in IP of s8 vs f32 

### ISSUE THREAD

**Issue by eladdidy** [intel/mkl-dnn#627]
# Summary
3 IP layers that I want to optimize by s8 quantization.
Running the process on single numa and affinity to core#2.
I have reliable time measuring code that is using time stamp register to measure execution times.

# Version
1.1

# Environment
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Platinum 8176 CPU @ 2.10GHz
stepping        : 4
microcode       : 0x2000030
cpu MHz         : 2799.985
cache size      : 39424 KB
physical id     : 0
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm hwp hwp_act_window hwp_epp hwp_pkg_req intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc

g++ 7.4.0

# Steps to reproduce
Attached example test code
build it and run with 'cset shield --exec -- chrt -r 1 numactl --cpunodebind=1 --membind=1 ./MKLDNN_GCC'

# Observed behavior
No improvement at all in execution time between the s8 and the f32

See test app log

rtsdc factor is 2095220060
count calibration for 96221 is 52423
Test FC float Time(us): 79 over 10000
Test FC float FC1 Time(ns): 1832
Test FC float FC2 Time(ns): 1762
Test FC float FC3 Time(ns): 1234
Test FC s8s8 Time(us): 71 over 10000
Test FC float FC1 Time(ns): 1670
Test FC float FC2 Time(ns): 1458
Test FC float FC3 Time(ns): 1238
Example passes

# Expected behavior
s8 it expected to run faster

[Test_s8_vs_f32.zip](https://github.com/intel/mkl-dnn/files/4033915/Test_s8_vs_f32.zip)

**Comment by eladdidy** [comment]
However if I increase the IP layers dims in test_FC_defs.h
L1_OUTPUT_WIDTH 600
L2_OUTPUT_WIDTH 600

I do see that s8 runs faster

**Comment by emfomenk** [comment]
Hi @eladdidy,

Thanks a lot for the reproducer!
The reason for s8s8 InnerProduct to not be faster than f32 is that very small sizes. In terms of gemm the sizes are:

| Layer | M | N | K |
| :-- | :-- | :-- | :-- |
| FC1 | 128 | 1 | 48 |
| FC2 | 64 | 1 | 128 |
| FC3 | 32 | 1 | 64 |

Given that s8s8 gemm requires data preparation to be able to execute the int8-intructions (some details [here](https://intel.github.io/mkl-dnn/dev_guide_int8_computations.html)), and given that for the biggest layer here (FC2) it is roughly ~512 fma-like instructions to compute -- the CPU is not able to come at the sustained efficiency. In other words, the overheads contribute to the time much more than the compute instructions them-selves.
Also, please note that on Skylake the int8 peak is only 1.3x higher than f32, and the biggest advantage on this platform typically comes from the memory reduction, rather than from the computation speed-up itself. And all these problems are so small that they are able to fit into L1 + L2 cache of the executing core -- hence no much gain from the memory speed-up either.

The long story short -- the problems should be bigger to see the gain from s8s8 compare to f32 instruction set. Otherwise you mostly see the effect of overheads of the computations rather than the effect of the computations themselves. 

The question is how big the problems should be to see the gain. I would say the M*N*K should be at least 64**3. See some data below.
I summon @aaraujom to comment more if I miss something.

---

I made few measurements on Skylake Platinum 8180:

``` bash
$ numactl -C2 -m0 -- ./benchdnn --ip --mode=P --dir=FWD_D \
   --cfg=f32,s8s8s32,u8s8s32 \
   mb64ic64oc64 mb128ic128oc128
```

| problem | F32 | S8S8 | U8S8 |
| :-- | :-- | :-- | :-- |
| mb32ic32oc32 | 34 GFlops | 34 GFlops | 38 GFlops |
| mb64ic64oc64 | 82 GFlops | 93 GOps | 107 GOps |
| mb128ic128oc128 | 119 GFlops | 144 GOps | 152 GOps |

**Comment by emfomenk** [comment]
Please also notice, that Skylake doesn't natively support `s8s8` combination, but only `u8s8` (see [this link](https://intel.github.io/mkl-dnn/dev_guide_int8_computations.html) I mentioned earlier). This requires us to make some additional computations to mimic `s8s8` by using `u8s8` instruction.
See the following comparison:
``` bash
$ benchdnn --ip --mode=P --dir=FWD_D --cfg=f32,s8s8s8,u8s8s8 mb1ic64oc128
```

| Problem | F32 | S8S8 | U8S8 |
| :-- | :-- | :-- | :-- |
| mb1ic64oc128 | 11 GFlops | 13 GOps | 17 GOps |

So, here `u8s8` is still notably faster than `f32` (even though the problem is really small).
