### ISSUE TITLE
what should I do when deconv  weights is iohw format

### ISSUE THREAD

**Issue by angus1121** [intel/mkl-dnn#633]
I am using the mkldnn v0.21. I find that  function mkldnn_deconvolution_forward_desc_init()  judge the param format must  be oihw, if my param is iohw format, should I must reorder the parma from iohw to oihw before the mkldnn_deconvolution_forward_desc_init function, Is there any else i can do, Is there any demo I can reference.

**Comment by emfomenk** [comment]
Hi @angus1121,

Though we don't have a complete deconvolution example, there were few related questions on the GitHub. Please take a look at #228 and #314.

I want to note, that in DNNL deconvolution expects the logical order of weights (parameters) dimensions to be in order {o, i, h, w}, where `i` is the number of channels in input image, and `o` is the number of channels in output image. In most frameworks the logical order of the weights is typically {i, o, h, w} but that is because they swap the meaning of _input_ and _output_ (as deconvolution implemented through backward pass of the convolution).
In other words, I suspect that even though you say your params are in iohw format, most likely that exactly what the deconvolution expects you to have.

The overall programming mode is the same as in convolutions (you can refer to the example with convolution primitives). The usage consists of the following steps:
1. Initialize a deconvolution operation descriptor with src (input), weights (params) and dst (output) memory descriptors which memory format is set to `any` to allow primitive to pick the best format
2. Create a deconvolution primitive descriptor.
3. Query the deconvolution primitive descriptor above for the src, weights and dst memory descriptors with the format the implementation wants.
4. Initialize the src and weights memory descriptors you have (in user's format, like nchw and oihw)
5. Compare the src memory descriptor you have (step 4) and src memory descriptor deconvolution expects (step 3). If they are different, create a new memory and reorder your src to the deconvolution's one.
6. Repeat the same for the weights. If multiple iterations are expected with the same weights, cache the reordered weights.
7. Execution the deconvolution.
8. If this is a final result, compare the dst memory descriptor from the deconvolution (step 4) with the memory descriptor of dst in user's format (like step 4). If there is a mismatch -- reorder the dst from the deconvolution to the user's dst.

If you want to measure the performance of deconvolution in DNNL, you may use [benchdnn](https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn) micro-benchmark.

**Comment by vpirogov** [comment]
Feel free to reopen or submit a new issue if you have further questions.
