### ISSUE TITLE
fragile #ifdef SIMPLE_IMPL in cpu_reducer.cpp

### ISSUE THREAD

**Issue by kruus** [intel/mkl-dnn#634]
# Summary
`SIMPLE_IMPL` preprocessor define in `cpu_reducer.cpp` seems fragile.

# Problem statement
`create_reduce_2d_drv` may return `nullptr` (if not mayiuse avx2 or better).
However a preprocessor define is used to select jit vs non-jit code path, which
allows the possibility of creating a jit impl and then not using it,
or (**worse**) not creating a jit impl, and calling via `nullptr`.
This affects the `reduce_nolock` and `reduce_block` methods.

# Preferred solution
Make `reduce_nolock` and `reduce_block` generic by replacing `#ifdef SIMPLE_IMPL` with
```
if(drv_) {
  /* existing code to call jit driver */;
} else {
  /* existing SIMPLE_IMPL code block*/;
}
```

Now `create_reduce_2d_drv` can independently decide whether to return `nullptr`
(separation of concerns, generic code, fewer ugly \#if blocks)

[opt.] If you wish to retain SIMPLE_IMPL for test compilations, just use it once, to force `create_reduce_2d_drv` to return `nullptr`. (I do something like this for non-xbyak compiles).

**Comment by kruus** [comment]
Oh, one of the SIMPLE_IMPL blocks uses `balancer_.nthr_per_group_` historical code, which should be changed to `balancer().nthr_per_group_` to compile.

**Comment by emfomenk** [comment]
Hi @kruus,

Long time no see!

While I was planned to say that `SIMPLE_IMPL` macro is not intended for any use (it is kept mostly to debug the code), I noticed that we might potentially have an issue on AVX (< AVX2) systems.
So I will take a look at possible solution. I will consider leaving the reference implementation as a fallback in case we cannot jit.

**Comment by emfomenk** [comment]
After a closer inspection the conclusion is we don't have any issues with pre-AVX2 systems.

There were 2 suspicious places:
- [`src/cpu/jit_avx2_1x1_convolution.hpp`](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/jit_avx2_1x1_convolution.hpp#L326-L327),
  - This one doesn't support AVX at all, and the reason seems to be a little deeper than just lack of reducer -- essentially the convolution kernel has yet to support <AVX2. 
- [`src/cpu/jit_uni_dw_convolution.hpp`](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/jit_uni_dw_convolution.hpp#L282);
  - This one doesn't explicitly support AVX either, but supports SSE4.1. For SSE4.1 there is a special code that performs accumulation (see [here](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/jit_uni_dw_convolution.cpp#L514-L522)) instead of involving the jitted accumulator as it is done [here](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/jit_uni_dw_convolution.cpp#L575-L576) for AVX2+.

What we could do is to add a new class (say `simple_reducer_2d_driver_f_s_32_t`) that will implement that same [interface](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/cpu_reducer.cpp#L96) as [`reducer_2d_driver_f_s_32_t`](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/cpu_reducer.cpp#L121), but would use pure C++ plus `PRAGMA OMP SIMD` (similar to `SIMPLE_IMPL` [here](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/cpu_reducer.cpp#L455-L465) and to the code in [depthwise convolution](https://github.com/intel/mkl-dnn/blob/d7b174baa207cf5b95c50cbff96cc2e5ee28da74/src/cpu/jit_uni_dw_convolution.cpp#L517-L522)).

This approach will simplify the code in depthwise convolution and support your use-case.
Given that there are no immediate issues with the current code and low priority of this insignificant improvement of the code I doubt I will work on it anytime soon. However, I am fine keeping this issue open and it being assigned to me.
Please feel free to take over it and open an PR with the enhancement. :)

**Comment by kruus** [comment]
Yes, long time -- we finally have internal clients and customers asking about support for the dnnl v1.1 API, so I'm looking now at compiling with xbyak disabled again.  For the VE processor, we now have decent speeds for many layers via intrinsics/JIT via external library calls, so the ref/gemm impls can be beefed up nicely with just a few selected additions to cpu\_engine.  So I think it's a *great idea* to leave those tiny reference impls, since I never have a jit impl available.

Currently I'm looking at how to harmoniously add a build-time analogue for the CPU max isa dispatcher, all the way down to ref impls (or C/C++ only).  I like the new `options.cmake` and `dnnl_config.h.in` mechanics.  Much cleaner than my previous build system.

**Comment by kruus** [comment]
OK, please leave the issue open and I will begin work on it after I have a new vanilla build working on VE (my high priority goal atm).  Then I'll delve into ref impl tests and timings in more detail. Probably in 2-3 weeks or so.

**Comment by emfomenk** [comment]
Sounds good!
And thanks for the update! I am glad to hear gen-dnn keep developing!

**Comment by kruus** [comment]
Non-urgent note to self (mostly)...

`cpu_isa_traits.cpp` is taking care to decouple `dnnl_cpu_isa_t` values from private `cpu_isa_t` bitmasks, and by v1.1 they have diverged a bit. So *technically* there could be future issues with calling the public `set_max_cpu_isa(dnnl_cpu_isa_t isa)` with a private `cpu_isa_t` enum value instead.  This happens in `tests/gtests/test_isa_iface.cpp`. 
It's OK for foreseeable future only because sse41 values happen to still match.
It's an issue I encounter when expanding the dnnl_cpu_isa and cpu_isa enums.

(simple fix: split off the conversion code in `set_max_cpu_isa` as a separate internal function, to get correct matching between args to `set_max_cpu_isa` and `mayiuse`).

**Comment by rsdubtso** [comment]
> cpu_isa_traits.cpp is taking care to decouple dnnl_cpu_isa_t values from private cpu_isa_t bitmasks, and by v1.1 they have diverged a bit. So technically there could be future issues with calling the public set_max_cpu_isa(dnnl_cpu_isa_t isa) with a private cpu_isa_t enum value instead. This happens in tests/gtests/test_isa_iface.cpp.

Just for clarification: I don't think this is the case. The test is calling `set_max_cpu_isa(cpu_isa::sse41);` where `cpu_isa` refers to `dnnl::cpu_isa` which is a public enum and not to `dnnl::impl::cpu::cpu_isa_t` which is an implementation detail.

The external enums should never be used anywhere except in the `set_max_cpu_isa()` or the `test/gtests/test_isa_mask.cpp` (and the lack of an extra common function is intentional here -- I want to test the translation...), so I thought that I could get away without having an extra common function. But this is probably a very x86-centric view... I'd be happy to improve this :)

**Comment by kruus** [comment]
Quite right.  Not the first time I forgot about `dnnl.hpp` mappings.  So now my `test_isa_iface` has both 'mostly-C' and a 'C++ish' versions of the test (to get more familiar with the distinctions).

I found my real problem was that the second call to `set_max_cpu_isa`
https://github.com/intel/mkl-dnn/blob/e1517b3cf9bf8426c78c0ed3ff0302ae6386a20b/tests/gtests/test_isa_iface.cpp#L28-L30
assumes `mayiuse` (line 28) causes
-- via `cpu_isa_t DNNL_API get_max_cpu_isa(bool soft = false)` --
a call to `set_before_first_get_setting_t<>::get` to happen,
so that line 29 does not succeed.

But with a vanilla "lowest common denominator" build, I wrote `mayiuse` had become a trivial constexpr _"false for everyone else"_.  So I add an explicit call direct call to `cpu_isa_t DNNL_API get_max_cpu_isa` in the gtest, which is closer in name and spirit to the `get` call whose side effect is being tested.

In more general cases, it can be tough too say much about the value coming from `get_max_cpu_isa`, so I add a bogus 'unknown' [I stole the 0 value] to `enum cpu_isa_t` and
`ASSERT_TRUE(impl::cpu::get_max_cpu_isa() != impl::cpu::unknown)`.

No need for changes atm, @rsdubtso .  First give me time to see how few diffs are actually needed nowadays to support a vanilla build -- my impression is that I _might_ be able to soon provide a fairly small change set to support compile/runtime limits on isa (all the way down to ref impls only).
  
Aside: Do the jit_uni_ impls also channel all their "CPU dispatch" via mayiuse too?  I'm wondering, because compile-time ISA targets cannot weed out those impls from cpu_engine.

**Comment by kruus** [comment]
I agree the function split is not desirable, and perhaps my more generic code can avoid it.  (I might only have done it to support some temporary debug paranoia).

**Comment by rsdubtso** [comment]
> Aside: Do the jit_uni_ impls also channel all their "CPU dispatch" via mayiuse too? I'm wondering, because compile-time ISA targets cannot weed out those impls from cpu_engine.

It's a ~~mess~~ mix of templating and `mayiuse()` last time I checked.

**Comment by kruus** [comment]
Questions while doing upstream merge with 2.1 ...  I appreciate the impl list splits.
- Can you confirm that a jit_uni_layer<avx2> requires mayiuse(avx2), as opposed to only avx2? 
- Should I assume that jit_uni_layer (no template parms) means mayiuse(sse41)?
  - or can this support x86 (maybe even without sse4.1)?

**Comment by emfomenk** [comment]
By saying `jit_uni_layer` do you mean jit_uni_layer_normalization.* files? If so...

> Can you confirm that a jit_uni_layer requires mayiuse(avx2), as opposed to only avx2?

The generated (via Xbyak) code inside works for avx2 and above (so `mayiuse(avx2)` is fine), but currently uses the instructions from `avx2` only; in future there might appear some `avx512_core` specific instructions, under the corresponding guards;

> Should I assume that jit_uni_layer (no template parms) means mayiuse(sse41)?
> - or can this support x86 (maybe even without sse4.1)?

Yeah, this file behaves different the most of the others. In most of the cases, `*jit*` in the name means that the primitive uses Xbyak to generate kernel, in which case at least sse4.1 is required (we do not generate code for pre-sse4.1 code). However, `jit_uni_layer_normalization_fwd_t` implementation has a fall-back kernels that are implemented in pure C++, and will be dispatched on pre-avx2 systems. We have similar situation in `gemm_inner_product_utils.hpp`.

**Comment by kruus** [comment]
I meant for generic "layer".  I'll begin by assuming `jit_uni_*` has _no_ pure-C++ fallback [easiest], and we can iterate towards something more correct as required (likely needs case-by-case edits to compile without  `jit_generator.hpp`).  Yes, having `gemm_inner_product_utils.hpp` to compile without jit_generator etc. is crucial because its post_ops ref impl got reused for a bunch of other layer types. Eventually rnn code might be able to do something similar (I disable rnn support in vanilla build for post_ops reasons now).

My inclination is not to split SIMPLE_IMPLs into a separate impls (at least to start with), because the amount of shared code/logic is high, and runtime overhead seems low.  Introducing optimization pragmas can still be done, just as easily.

My PR goal plan is to adjust cmake options to provide an "cmake -DDNNL_ISA=VANILLA" build. Naturally this build enables a number of SIMPLE_IMPL.  For now I will reproduce "existing behavior" for C++ fallbacks in the full build, though.

Does this seem like a good compromise for your and my interests?

Consider, however, that if fallback impl path were always available, you could run the full build and in principle do runtime CPU dispatch to VANILLA to only use the fallback or ref impls.

On the other hand there's also a use for forbidding, or at least detecting, that a fallback impl was used (at very least in the info string).  What do you think of a [far future] cmake option that defaults to "current behavior" (layer-specific), with options to always-allow, always-warn, or always-abort C++-only fallbacks of jit-capable routines?

**Comment by kruus** [comment]
OK, I found a clean, simple solution.  It is indeed correct the the ref impl is never really needed for the reducer, and that cpu dispatch to lower isa's and vanilla is unaffected.  However, the file name and excellent docs in `cpu_reducer.hpp` suggest it should at least be _available_ for non-x86 builds.  So `#define SIMPLE_IMPL !TARGET_X86_JIT` makes me happy, while keeping the default build unchanged. You guys remain responsible for never using the reducer in unsupported x86 jit cases. PR "coming soon".
