### ISSUE TITLE
convolution forward propagation with or without bias

### ISSUE THREAD

**Issue by FighterNan** [intel/mkl-dnn#638]
# Summary
In the file `mkl-dnn-1.1.2/include/dnnl.hpp`, the description of with bias or not about `convolution forward propagation` is flipped. 

# URLs
[This file](https://github.com/intel/mkl-dnn/blob/v1.1.2/include/dnnl.hpp)

# Additional details
Line 2041 should be `Initializes a descriptor for convolution forward propagation with` not `Initializes a descriptor for convolution forward propagation without`.

Line 2066 should be `Initializes a descriptor for convolution forward propagation without` not `Initializes a descriptor for convolution forward propagation with`.

The same for line 2090 and line 2117.

**Comment by emfomenk** [comment]
Indeed. Thanks for the report!

**Comment by emfomenk** [comment]
Oh, it turns out the documentation is already fixed by @rsdubtso in DNNL v1.2+ (e.g. see [here](https://github.com/intel/mkl-dnn/blob/v1.2-rc/include/dnnl.hpp#L3095-L3131)).
Given that this is a minor typo and it is already fixed in the latest release I am reluctant to back-port the change to DNNL v1.1. Hence, closing the issue.

Thanks for the report and thoughtful reading the documentation! :)

**Comment by FighterNan** [comment]
Got it. Thanks!
